### ISSUE TITLE
Jumping strategy

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1025]
Hello, 

Actually, if your commander dies, you can't make a jump pad.
Is it possible to delete jump pad from assault commander, and add this structure for Helper. 

If you want to rush with jump unit (TLL), you have to make T2 lab + assault commanders (12Km).
If you want to rush with jump unit (Core), you have to make T2 lab + assault commanders + RS (17Km).
=> too much resources.

Can we add jump feature for battle commander ? (small jump at 500 range & 60s reload)
Can we add jump feature for Commando ? (built by helper to make sense) (Mini jump)

#1024

**Comment by nixtux** [comment]
Core and tll jumpbot no longer need jump pad to operate so non issue, it's only for commander jump now

**Comment by skymyj** [comment]
Good thing :).
