### ISSUE TITLE
Barrett nerf

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#1027]
Yeah it's op, this thread is about ideas about Barrett nerf

**Comment by skymyj** [comment]
Just decrease Aoe (50%) & damage/s (-10%). 
Actually, destroy all T1 T2 easely.

**Comment by keijj0** [comment]
Yesh, barret is op and works as expensive defense. So imo range needs to be reduced to about same range as tacnuke, agree with sky on those aoe + dps nerfs. Also reduce buildcost by 25% and energy usage by 33%

**Comment by skymyj** [comment]
> Yesh, barret is op and works as expensive defense. So imo range needs to be reduced to about same range as tacnuke, agree with sky on those aoe + dps nerfs. Also reduce buildcost by 25% and energy usage by 33%
:+1:

**Comment by nixtux** [comment]
https://github.com/n3wm1nd/TA/commit/78c2a98c717d8bea84517384fbb46c0c8e7eb87a

**Comment by nixtux** [comment]
Closing
