### ISSUE TITLE
Balance Hero Arm & Core with TLL

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1032]
I Propose less damage for main weapon (-35% for arm) & (-37% for core).

We will have ground damage : 
- Arm : 26K DMG (Canon), 1000000MaxDamage for 300K Metal
- Core : 9K DMG (Rocket), 18K DMG (Laser), 1000000MaxDamage for 300K Metal
- TLL : 10K DMG (Canon), 2K (Laser), 450000 MaxDamage for 230K Metal

Good balance imho (note : no need to have T4 or Lab to make TLL Hero, so it's a high cost).

**Comment by nixtux** [comment]
valaint is mini hero dont balace v arm/core heros

**Comment by skymyj** [comment]
Its not just with valiant. It's for all opposites units. 
1 unit with 40k dmg /s is just op. The best unit after are valiant,  corgala , hyperion.
If yiu compare them, there is just a blance to make.
