### ISSUE TITLE
Tll Dgun

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1058]
Nix, there is a bug. Com cant dgun small unit...
Aoe is too low i think. 

http://replays.springrts.com/replay/2da352575c661ceaa2973eb16767a815/

**Comment by nixtux** [comment]
Fixed will push new release later

**Comment by nixtux** [comment]
https://github.com/n3wm1nd/TA/commit/8f21707000a7022aa299a58f9091d525584d1109
