### ISSUE TITLE
Remove end game weapons

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#1062]
I think tsar and T3 nukes need to be removed

**Comment by skymyj** [comment]
hello Nix. 
imho tsar is an ugly unit. So no prob to delete it. 

For Nuke, I think, we just keep this structure. But Add an Anti-Nuke for TLL.
And increase speed for T3 Nuke.

**Comment by nixtux** [comment]
So tsar's and tllion to go then ?

**Comment by skymyj** [comment]
Tllion i don't know.

**Comment by Senna** [comment]
omg, u guys are killing TA, Check out some stats on my geomaps, also absolutors didnt needed to be removed....

**Comment by nixtux** [comment]
Ok so how do I put seena on ignore here, same boring bs all the time

**Comment by Kaka5hi** [comment]
I'm for removing that weapons, 
- TSAR
-  Tllion (remove or not - its kinda end of game weapon in good hands) - or maybe increase cost...
+ tll needs t3 anti.
+ increase speed for T3 Nuke.
btw. Rapid Vulcan and Super vulcan should cost more.
