### ISSUE TITLE
Add damage stats from ba

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#1074]
Add gadget/widget combo to record units stats http://imolarpg.dyndns.org/trac/balatest/browser/trunk/luaui/widgets/stats_damage.lua
http://imolarpg.dyndns.org/trac/balatest/browser/trunk/luarules/gadgets/api_damage_stats.lua

**Comment by skymyj** [comment]
Is it possible to have a better visibilty about damage vs unitclass?
Dmg vs commader, air...

**Comment by nixtux** [comment]
A small explanation of what this will do https://springrts.com/phpbb/viewtopic.php?f=44&t=35188#p578294

**Comment by skymyj** [comment]
Reduce com wreck from 2500 -> 1250	Currently game revolves around self d of commander, a negative side effect of an incentive system gone wrong. Killing com instantly earns you a t2 lab of your choice, breaking t1. Often 2 commanders will die at once which is 5000metal for whoever gets it. This can buy you a fusion or a t2 lab and 2 goliaths, far too much reward and a high incentive to combomb for m.

I m for a 1250 metal given by com t1. For eco 2500 could be good and 2750 for battle.

**Comment by nixtux** [comment]
Make a new issue for that skymyj

**Comment by Senna** [comment]
TA=/BA no need to reduce com metal, its already reduced, also in BA T2 is 60% cheaper than in TA and i mean all t2 eco
