### ISSUE TITLE
T1.5 cons (vehicle) unlock all t1.5 units

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1075]
Is it possible to delete this. 
Actually i make a RC then t1.5 vehicle then i reclaim RC. 
Free unlock with cons that make adv structure is a little op

**Comment by nixtux** [comment]
im fine with this change

**Comment by nixtux** [comment]
which unit's ,unitname please

**Comment by nixtux** [comment]
as fred and marv dont

**Comment by skymyj** [comment]
It's fred and marv. 
You can test.

**Comment by nixtux** [comment]
They have no providetech custom parameter in there unitdef you sure about this?

**Comment by skymyj** [comment]
Yes im sure.
I think i already open an issue few months ago about this.
I deleted the customparam but not tested if it worked.
But now i can confirm it not worked

**Comment by nixtux** [comment]
https://github.com/n3wm1nd/TA/commit/4913d19c8d4c93b1e0557cd1668d98f5b3f09822
