### ISSUE TITLE
Wreckage for commander

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1076]
Reduce com wreck from 2500 -> 1250 Currently game revolves around self d of commander, a negative side effect of an incentive system gone wrong. Killing com instantly earns you a t2 lab of your choice, breaking t1. Often 2 commanders will die at once which is 5000metal for whoever gets it. This can buy you a fusion or a t2 lab and 2 goliaths, far too much reward and a high incentive to combomb for m.

I m for a 1250 metal given by com t1. For eco 2500 could be good and 2750 for battle
8k for assault
12k for star
16k for supreme

**Comment by nixtux** [comment]
i think 
1250 std com
2000 eco
2750 battle
9k for assault
20k for star
35k for supreme

**Comment by skymyj** [comment]
Im Ok with this.

**Comment by Senna** [comment]
doing this remove the option for com jump, otherwise the assault com is op, just jump in base and gg

**Comment by nixtux** [comment]
What are you talking about senna, the current metal amount for assault is not much difference from new suggested values

**Comment by skymyj** [comment]
Im with senna for t2 have high cost vs ba.
But 2.5 too much imho. 
1500 std com
2000 eco
2500 battle
9k for assault
20k for star
35k for supreme

**Comment by skymyj** [comment]
I begin with ArmCom. 
Are you ok with these change ?

**Comment by Senna** [comment]
leave the coms as it is pls, you will disbalanbe the stat game changing it

**Comment by Senna** [comment]
leave the first coms i mean, wich the important ones, late coms are is ok for a change

**Comment by skymyj** [comment]
Actually value is at 2000. We just decrease from 500. 
In TA commander is very important. 
So i know that you lost 500m if you autodestoy your com for tech. But I think we have to leave the BA teching path.

**Comment by skymyj** [comment]
I change only assaut, Star & Supreme Commander.
We need more reflection to take decision for standard commander.

If we decrease too much, the combomb will increase until kill the game in team.
