### ISSUE TITLE
Delete units never used and others reasons

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1086]
First in this list are : 
- Copters cause cost too high, no cons copter, too weak vs air, same job than gunship air...
- Dragon cause we are not in Total Annihilation Kingdom neither Transformer Movie ;)

**Comment by nixtux** [comment]
Let wait and see what data I get in next release from this https://github.com/n3wm1nd/TA/commit/d789854866186acb83840cc50d686d5e932ebee6

**Comment by Kaka5hi** [comment]
Dragon cause we are not in Total Annihilation Kingdom neither Transformer Movie ;) - tre dat :D:D:D

**Comment by nixtux** [comment]
Also the data set needs to come from a large spectrum of maps!!!

**Comment by Kaka5hi** [comment]
yes copters are useless now. I tried use them many times, and I faild.  

I see 3 variants:
1. Remove them or 
2. Speed them up or
3. Buff flak resistance

**Comment by skymyj** [comment]
@nixtux : Sure that is not ship & amphibious that be used in techno-land :)

**Comment by skymyj** [comment]
Nix, what did tell your widget ?
