### ISSUE TITLE
Junos

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#1089]
Option 1, unit limit for juno production 
Option 2, add extra check in gadget to limit damage to units with under say 1200 max hp

**Comment by skymyj** [comment]
i dont understand what's wrong with juno ? 
They inflict 1 or 5 dmg to each unit ?

**Comment by Kaka5hi** [comment]
-  i would limit number to 25 (25x 20dmg x 3sec = 1500dmg) - in real test ~1220dmg max
- limit dmg to units under 1200hp (for example) will make juno useless against aka/peewee spam
as that feature was created for that purpose.

**Comment by Kaka5hi** [comment]
tested along various units - why dmg calculation not match real test ?
in centre of shoot max was 1220dmg (should be closer to 1500)

**Comment by nixtux** [comment]
Damage has an area and time falloff rate, ie less damage over time period/area, btw we can limit stockpile amount

**Comment by Kaka5hi** [comment]
last game show that is hard to overuse junos, its easy kill them, hard to build many junos close enemy.
imo limit to 20 is ok. maybe some stock pile limit idk.
They are not too op :P

**Comment by Kaka5hi** [comment]
I have simplest idea, not sure if easy to implement:

- just set in that configuration that damage for kbots and tunks is 20 x3
- default 5 x3
- no need to limit junos in any way

**Comment by nixtux** [comment]
Damage for kbots and tanks is 20 x3 (in that config)  -- yep sound easy :D but not

**Comment by nixtux** [comment]
Easiest way is to check unit initial HP, all other ways are a lot more work

**Comment by Kaka5hi** [comment]
how it will work?

**Comment by nixtux** [comment]
Fixed in https://github.com/n3wm1nd/TA/commit/2fd7ac7ea1af601cbedc2e20bf6d24ab571fa1c8
