### ISSUE TITLE
DamageModifier

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1096]
Is it possible to fix to 0.10 : 
-Cordoom 
-Tachyyon ARM & TLL
-T3.5 ARM nsaagriz

I clean up damage / s (same balance)
I add damagefor commander for cordoom (green & red weapon for v1 & green for v0)

#1095

**Comment by nixtux** [comment]
Why do you want to make it harder when there closed, nope not going to happen

**Comment by skymyj** [comment]
My goal was to counter long range rocket t2. 
Core has an advantage with cordoom. 
Actually arm suck vs dominator units. 
But i'm fine with this (and my ts too).
