### ISSUE TITLE
Add T2.5 vehicle : vaporiser

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1097]
Is it possible to rework this unit. 
Job : Kill big t2 unit at short distance like armcd
![armcd](https://cloud.githubusercontent.com/assets/2990630/16546666/2c839e7c-4152-11e6-9772-fd846e508b9a.png) = ![vaporiser](https://cloud.githubusercontent.com/assets/2990630/16546670/45f80870-4152-11e6-9617-e41e260c4b9a.png)

**Comment by skymyj** [comment]
We coud add a morph with dao => vaporiser

**Comment by nixtux** [comment]
Meh I hate the way armcd is already, and don't change vaporise weapon effect, it's different so keep it

**Comment by skymyj** [comment]
why did'nt you want to change weapon effect. This unit could be nice & balanced (i tested). 
Maybe we should delete armcd?

**Comment by skymyj** [comment]
Better to change weapon & use this unit than let it die
