### ISSUE TITLE
[BUG] Graphical glitches since engine 101 was implemented.

### ISSUE THREAD

**Issue by DeathStarSPRING** [n3wm1nd/TA#1101]
[BUG] Graphical glitches since engine 101 was implemented.  It seems to be triggered when pointing your mouse at a metal wreck like seen in the screen shots below:
http://imgur.com/a/6hxQc

I am not sure if its engine-related or Tech Annihilation-related.
Please address this issue.
Thank you.

**Comment by nixtux** [comment]
102 is here now so please recheck, reopen if needed
