### ISSUE TITLE
TA COMS TOTAL OP NOW

### ISSUE THREAD

**Issue by Senna** [n3wm1nd/TA#1120]
TA now is total OP with com, they not being killed by air combomb is total unfair. Remove TA com morph or enable combomb by air

**Comment by skymyj** [comment]
Hard to kill battleCom with T1 & T1.5
I propose : 
- combomb like BA
- less damage vs Air (banshee or paralyse drone)

**Comment by skymyj** [comment]
And Same speed than classic commander. 
(to easy to kill com without die)

**Comment by nixtux** [comment]
Combomb is the same as BA, closing issue (mud)
