### ISSUE TITLE
Armanni1 & Cordoom1 VS T3.5 Battery

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1160]
Hey, 

- Is it possible to remplace Armanni1 & Cordoom1 by T3.5 Battery (Nebraska & ??) for T3 Cons ?

- Is it possible to delete  T3.5 Battery for T2 Cons ? 

=> They are OP vs tachyon vs Cordoom & it's logic we have to find them on T4 tech.

**Comment by nixtux** [comment]
It's anti t3 battery so need to be build around the same time, if it was in t4 con it will be too late to be effective imo

**Comment by skymyj** [comment]
These units kill easely T3. 
You have to spend 18k Metal to make this unit. and it kills easely two krogoth. (if energy).

So : 
First : increase cost. 
Second, delete from T2 cons.

**Comment by skymyj** [comment]
First goal is to inflict many damage. Usefull versus T4 unit & more versus T3 (cause less hp)
