### ISSUE TITLE
T3 Invisible Bomber TLL

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1228]
Nix, 

I think there is a prob with T3 Bomber. 
For Arm / Core, T3 Research center can add timing before meet these weapons on battlefield.
For TLL, I think the heavy bomber is better in stats but very expensive too. It's risky for player who want to play with low resources. 

But for invisible bomber, it's very unbalanced imho. 
I propose to transform this T3 bomber into T3 Torpedo. 
I think it's better and will rebalance the T3 naval TLL.

**Comment by nixtux** [comment]
Fine do it
