### ISSUE TITLE
Remake Icon for T2 TLL

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#1257]
Actually, If you dont know the game, it's hard to see what unit you want with T2 Kbot TLL. 
Same for vehicle. 

I propose this : https://1drv.ms/i/s!AgjKPxaKD1zLhBF6nOFJJS_UTLWQ 
For Rocket Kbot.

**Comment by nixtux** [comment]
Wont be done until this issue is fixed https://github.com/n3wm1nd/TA/issues/218
