### ISSUE TITLE
Is this the best resource for reporting bugs?

### ISSUE THREAD

**Issue by Leggir** [n3wm1nd/TA#1353]
I'll admit, I play Tech Annihilation more than any other game by far. I've got friends playing it too. We always download the latest distro just to see what changes you've done. Is this the best resource for reporting bugs? Do you want help in identifying bugs? How many developers are working on this?

**Comment by skymyj** [comment]
Hello Leggir. There are 3 developpers : Nix (main), Silver and me. 
You can add all issues you saw in the games.
You can also with github propose request about balancing, bugs.... After each request, there is a vote and if majority is, your request will be merged.

**Comment by skymyj** [comment]
All request merged here are automaticly implement in version-test on lobby.

**Comment by skymyj** [comment]
The best is to post all issue and request with our new github site : https://github.com/techannihilation/TA
