### ISSUE TITLE
EMP Time Rebalance

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#481]
Actually, a Spie bot can emp +40s units.
Vs 8s for 10 emp bombers, or less for emp bertha or emp extractor metal.

Nixtux, can we have time for each unit ?

Maybe, should be good to rebalance like this : 
- Spie Bot (arm & core) : 20 seconds
- Bombers : 8 seconds + 2 seconds per bomber (or 5 bombs...)
- Emp tactic (Arm & Tll) : 20 seconds
- Bertha : 12 seconds
- T3 Vehicule TLL : 12 seconds
- Extractor Arm : 20 seconds
- T1.5 Paralyser : Actually good balance
- Drone Paralyser air t1 Core : Actually good balance
- T3.5 Bot Arm when die : ???
- T3 TLL Ultimate Paraliser : good balance
- T1 Turret TLL : ???
- EMP Bomb : ???

Thanks

**Comment by nixtux** [comment]
we all ok with currect balance if so will close issue

**Comment by skymyj** [comment]
Ok for me. If bomber emp 10s :)

**Comment by skymyj** [comment]
EMP Bomber have now 7s... 
Just not enough. 
Please, make 12s like before or 14s

**Comment by SoulRaiZor** [comment]
7 secs makes them useless true

**Comment by nixtux** [comment]
Lucky I set it to 8 seconds then :P, no idea why I did that will set them back to 14?

**Comment by skymyj** [comment]
!vote y for 14s

**Comment by nixtux** [comment]
Emp time set to 13 seconds, closing issue now reopen if anything else is off
