### ISSUE TITLE
Adonis Balance

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#500]
Actually, it's a 6k metal cost with tech Center 2.5. 
& just 450 dmg / s.. Can't Be. 
To change : 
The laser : 3k damage every 9s & 950 range. For an approximatly 350dmg/s
The missile can't shoot on side. Only by front. It's a not an advantage.. So they have to have more power like 1200 dmg (each) every 4.80seconde. For an approximatly 470dmg /s
![coradon](https://cloud.githubusercontent.com/assets/2990630/5231686/276461fa-773d-11e4-8c81-a6ef691130d7.png)

**Comment by nixtux** [comment]
tempest (core counterpart) would need a minor buff also
