### ISSUE TITLE
menacer unit to rebalance

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#529]
Spider artillery never use like all spider. 
But cost too high no hp & no range & no damage / second...

actually worst unit ever.

**Comment by skymyj** [comment]
& I suggest to delete all spider & copter for 2015 :)

**Comment by SoulRaiZor** [comment]
Spiders are just not used because we play not much maps with hills.
On Wide Pass ppl use spiders.

Iam fine with copters

**Comment by skymyj** [comment]
All the units (spider) (except these included on BA & eventually the artillery spider) are useless in strategic or in visual design. Better to included 2 models by faction on T2 lab.

**Comment by skymyj** [comment]
All the units (copter) are useless in strategic for TA. 
I suggest : 
- Delete them
- Rebalance them in adding AA missile  (they have to destroy all units : AIR & GROUND). Actually, air fighter are too strong or defense ground again too strong vs them).

**Comment by SoulRaiZor** [comment]
Yesterday i played dsd vs some guys which used copters.
They did a very good job.
I changed my opinion, let them in ;)

**Comment by skymyj** [comment]
Nix, what is your decision about this unit ?
