### ISSUE TITLE
Anti-Nukes should fire more than 1 anti to prevent a nuke breaching suggestion.

### ISSUE THREAD

**Issue by DeathStarSPRING** [n3wm1nd/TA#530]
Anti-Nukes should fire more than 1 anti to prevent a nuke breaching suggestion.  
Example, if you have 3 antis, and 2 antis are in the circle where the 1 nuke is being fired, both antis should fire 1 anti to stop the nuke, in case a player decides to fly his units over 1 anti, causing 1 anti to blow up before hitting the nuke, so the other anti can hit the nuke and prevent breaching.  This would also eliminate bugs being taken advantage of, such as the t2 core anti hedgehog which would miss before (I know this was fixed, but this would eliminate such future bugs from being taken advantage off).
In my opinion, 3 antis maximum should be fired for each nuke, but that is up to you.
Please consider adding this feature if possible.
Thank you Nixtux :) .

**Comment by SoulRaiZor** [comment]
That doenst make sense, so its easy to outspam with nukes.
