### ISSUE TITLE
Champion Tank

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#533]
Hey!
Chapion Tank has way too much HP for its cost.
Its about 2300 with 25k hp.
Should be reduced to 12.5k hp

**Comment by skymyj** [comment]
You can test 4 champion vs 1 bantha & good balanced

**Comment by SoulRaiZor** [comment]
another game ruined by those tanks, they just walk through banthas and kill base before u can kill them.

**Comment by skymyj** [comment]
So, don't change stats but increase metal cost. Like 3.5k

**Comment by skymyj** [comment]
You make T3, for T2 TAnk.... I see sumo laugh :)
Totally useless... 
Make +20k hp & 500dmg/s & more cost metal please. Or make it in T2.5 unit !!!

**Comment by SoulRaiZor** [comment]
u cant compare that with a sumo.
Sumo is damn slow, those tanks can rush.

**Comment by skymyj** [comment]
Ok, so make more speed again.
But I'm for a high Hp tank. Increase cost is best way, I think

**Comment by skymyj** [comment]
Nix, what is your decision ?

**Comment by skymyj** [comment]
On last game, T2.5 unit kill them so easely... 
Please delete this unit or make them +25ke with 3.8k metal cost

**Comment by SoulRaiZor** [comment]
U had t3.5 tigers which killed them

**Comment by skymyj** [comment]
After test. I vote for same HP than SUMO. 13K HP sounds good.

**Comment by skymyj** [comment]
I tested them again... You just have destoyed this unit.
New suggestion : Equip them with same weapon than juggernaut (plasma pass over ennemy unit). Increase hp to 35k. Decrease speed.  Metal & energy cost * 2.5.

**Comment by SoulRaiZor** [comment]
If u increase it that way its balanced, yes. 
But then its another unit class (bantha like).
Depends on nix' idea of this unit.

**Comment by skymyj** [comment]
Nixtux, So what is your decision about this unit ?
