### ISSUE TITLE
Lobby FFA mod

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#534]
Hey!
Yesterday we wanted to make some big FFA, but its not really easy to handle, because nbteams 16 for example is blocked.
Is it possible to unlock it, or make some !ffa 1 which automatically switches settings to ffa?
Thats startpostype and teams (maybe i forgot one)

**Comment by nixtux** [comment]
Done
use !list bpresets 
atm there is only default and ffa
if you can think of anymore just reopen issue

**Comment by nixtux** [comment]
Ok option names now are team or ffa

**Comment by nixtux** [comment]
Command level set correctly now all trusted users and above should be able to use !forcepreset now

**Comment by SoulRaiZor** [comment]
just for all players: 
command is 
!forcepreset ffa
and
!forcepreset team
