### ISSUE TITLE
our new ffa setting isnt working

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#535]
Hi!
I set ffa mod on and we started a game, but we didnt get a commander.
After stopping the game we wanted to go back to normal settings (ffa), so i switched to team, !nbteams 8 and we wanted !bset startpostype 1, which didnt work anymore.
So the server settings were messed up.
Even rehosting didnt fix it.

**Comment by nixtux** [comment]
odd seem to work fine here atm, reopen if it happens again
