### ISSUE TITLE
Idea for Defiler & Terroriser (actually useless unit)

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#538]
Defiler = Make it all terrain like Cavalier (T2.5 Arm Kbot). No all terrain in T2 Core Lab. + Design unit is perfect for all terrain.

Terroriser is under powered & useless for t2.5 unit. Tankanotor is better & have same fonction.
Is it possible to transform Terroriser in Mobile Screamer 	(Long-Range Missile Tower). With maybe less range & same cost ?

![03](https://cloud.githubusercontent.com/assets/2990630/5745292/e5e93c0e-9c27-11e4-83ae-d8b8f73d980f.png)
Defiler
![01](https://cloud.githubusercontent.com/assets/2990630/5745293/e60c329a-9c27-11e4-898f-9981193bef02.png)
Mobile Screamer
![02](https://cloud.githubusercontent.com/assets/2990630/5745294/e60e9cb0-9c27-11e4-9297-72b4d0a5c93a.png)
Terroriser

**Comment by nixtux** [comment]
Hmm I thought defiled was all terrain, will fix that, let me think more about the other one

**Comment by skymyj** [comment]
Don't forget to change descriptif unit too. Actually, there is no precision for "All terrain unit"

**Comment by nixtux** [comment]
No change needed for defiler as it already all terrain just missing description, and won't change terroriser to mobile mercury/screamer (even with high cost I think unit will be op)
