### ISSUE TITLE
Krally - Fast Assault Kbot t2.5 Core

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#543]
Good unit but cost too high. 
Should be good to decrease energy cost (40ke => 12~14ke). (for comparaison, krogtarr have same energy cost...)
Is it possible to deseable explosion when they die (but let explosion if autodestroy) ?

**Comment by SoulRaiZor** [comment]
I dont know any tactic with Krally, i just saw a match where krally were a bad bad choise.
How do u use it?

**Comment by skymyj** [comment]
I opt for the same strategy than Zipper. They have good HP/armor, so you can use them (8-12 units) & their speed make them easely pass over T2 defense & destroy economy.

So, I recommend : 
- To decrease cost (-10% metal & -60% energy)
- to delete explosion after they die (destroy others Krally in chain... So if one or two die, the rush is broken). 
- that they can pass over teeth.

**Comment by skymyj** [comment]
I'd like to replace the lighting wepon (for arm unit) by a green laser (same dmg/s)
I'd like to delete them the missile launcher (useless for the strategy of speed kbot) & add them a feature as : jump or/& self repair or/& plasma shield reflector ;

**Comment by nixtux** [comment]
Made changes here please test

**Comment by skymyj** [comment]
I just have tested them. Perfect for me. Good work :)

Could be good to have a jump unit for arm too.

**Comment by skymyj** [comment]
- There is not green counter to see time left before n,ext jump
- After they die, they explose. Is it possible to delete this ?
- They see <500. Is it possible de increase to 1000 ?

**Comment by nixtux** [comment]
reload bar works for me,2nd will fix, 3nd what not sure what you mean

**Comment by skymyj** [comment]
Their visibility is too low. They can't shoot correctly cause they see nothing.
