### ISSUE TITLE
Star Commander : Special Unit

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#547]
Actually, Star Commander have no special weapons or features (except units added for Christmas).

Is it possible to add a new unit : Fake Commander with same design than Assault Commander.
It could be : 
- Have weapon like laser & Dgun (15k/hit)
- Produce 500e/s & +8m/s
- Have Plasma Shield Deflector,Terraforming, Jump & Capture.
- Same explosion than Assault commander (10s counter)
- Menu Panel for structure build :
** T2 Defense (Annihilator, doomsday, pop-up, Flak, T2 Torpedo), T2 Radar, Mines, Plasma Deflector, Light Fusion, Metal Maker adv, T3 unit (Razorback or Karganeth), Tac Nuke or Emp...   

What do you think about it ?

**Comment by nixtux** [comment]
No already explained that I don't want to add decoy commanders, closing issue

**Comment by skymyj** [comment]
armamd & corfmd can morph with T3 Tech Center. 
armscab & cormabm can morph with no Tech center.

I propose to unlock mobile anti-nuke with T3 Tech Center.
