### ISSUE TITLE
AntiNuke Mobile

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#549]
Actually, they can morph with no Tech Center. 
Is it possible to unblock with T3 Tech Center as Fix Anti Nuke (actually) ?

**Comment by nixtux** [comment]
What fix I'm lost, explain more please

**Comment by nixtux** [comment]
No feedback closing issue

**Comment by skymyj** [comment]
I posted but don't appear...
I just want to lock the morph with T3 Tech Center. (like antinuke armamd)
