### ISSUE TITLE
Vanguards plasma cannon goes through Supreme Commanders shield

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#550]
plz fix

**Comment by nixtux** [comment]
Wrong it does not (shieldpower "hp" is greater than weapon default damage) , star commander is a different matter (1200 shield power < 1250 default damage from armshock), unless you did mean star commander ???

**Comment by SoulRaiZor** [comment]
this means shield can only block shots with <1200dmg and if i fire with dmg 1500 on it 300 will go through?
Or am i wrong?
Can u give me an example plz.

**Comment by nixtux** [comment]
Shield power the maximum allowed hit-points of the shield, which  is reduced by the damage of a weapon upon impact, so is current hit point is great that default damage from weapon it will repulse shoot

No shoot will go though and all damage will be done

**Comment by nixtux** [comment]
Soul so non issue ?
