### ISSUE TITLE
T3 anti is too slow

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#552]
Hey!
T3 Anti nuke is too slow to get nuke.

T3 nuke got launched, after that my anti finished, but couldnt get the nuke anymore, because its on same speed.

Maybe a little change?

**Comment by nixtux** [comment]
I'm not sure it would had hit anyways if anti was complete after nuke launch

**Comment by skymyj** [comment]
I Think, we should have same speed than nuke. 
It's not a T4 nuke but a turtle nuke..

**Comment by nixtux** [comment]
I think it quite funny that it trolls you, hahaha I'm coming but you forgot anti

**Comment by SoulRaiZor** [comment]
ya iam fine with nukespeed, incredible moment :D

**Comment by nixtux** [comment]
Won't change anything here due to how slow nuke speed is
