### ISSUE TITLE
T2 Nano

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#555]
I saw this issue : https://github.com/n3wm1nd/TA/issues/362 

I'm for T2 Constructor can build T2 Nano & no defense structure. (except experimental canon anti T3/T4).
There will be no more unit in menu panel. 

Instead of engenereer than can build T1 Nano & defense structure (annihilator, flak, pop-up, plasma... )

**Comment by nixtux** [comment]
Won't happen, we have quite a few players for ba cross over changing build menu will just confuse thoses players closing issue, and I've already stated in other thread why nano's won't happen
