### ISSUE TITLE
Reloading speed of DMC

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#559]
Hi Dark Matter Cannon isnt loading fast enough for its cost.
Plz fix it

**Comment by nixtux** [comment]
Did you noticed tlldmc does 3x damge to experimental unit compaired  to boucher/nebraska, while reloadtime is just over 3x longer > 5 sec for arm/core and 16 sec for tlldmc

**Comment by SoulRaiZor** [comment]
hmm problem is:
if i send 1 single scout (t1, t2, t3 cheapest unit) in front of my army the dmc shoots at it and within 16 secs my army is next to the dmc.
I saw following example:

1DMC and some Laser towers and such (cost ~150k)
vs Krogots and small t3 shit (cost ~120k)

u wont believe it, but the krogots and small t3 units won this easy.
There were units (cost ~ 60k) left, after all def was destroyed.

And it had no bad placement or such.


Result:
Somehow def in general isnt working good. 
And DMC in special

**Comment by skymyj** [comment]
These canon anti T3 take too much energy to let them in "Fire at Will". 
Player have to select manually ennemies units.

**Comment by SoulRaiZor** [comment]
That makes defing much harder than attacking.
And if u have more than 2-3 DMC its uncontrollable.
I think most people cant even coordinate 1.
Or they simply dont know that they have to.

In my opinion it shouldnt be a superweapon only for pro players.

**Comment by nixtux** [comment]
Ok so im proposing to give tlldmc 2 weapon mode std or rapid fire, thoughs please

**Comment by nixtux** [comment]
4 second reloadspeed v 16 of std mode, will also reduce damage and cost x4

**Comment by skymyj** [comment]
Fine for me.

**Comment by SoulRaiZor** [comment]
should be much better than.
Dont forget to decrease cost / shot :D

**Comment by nixtux** [comment]
Pushed changes test please, will close for now
