### ISSUE TITLE
OPS T4 Center will not make units if a nano level 3 is built right next to it

### ISSUE THREAD

**Issue by DeathStarSPRING** [n3wm1nd/TA#565]
OPS T4 Center will not make units if a nano (in this case, a level 3 nano) is built right next to it.
Here are some screenshots:
The nanos' location relative to the research lab:  http://imgur.com/s18n3zE

The bug:  http://imgur.com/7jG0ByJ
Maybe it has to do with the nanos being level 3 while being too close?
Please address this issue.  Thank you.

**Comment by nixtux** [comment]
What's causing that's is the fact the units is larger than the unit it morphed from, so the nano's are now inside the units building yardmap which then causes the engine to block building from lab, easy fix just need to reduce unit size

**Comment by SoulRaiZor** [comment]
or make  tech centers all the same size?

**Comment by nixtux** [comment]
@soulraizor and change the way tidal pools are made? :D

**Comment by SoulRaiZor** [comment]
U can decrease explosion range so that it will make a pool with same size

**Comment by nixtux** [comment]
With an increased size of rc you would not be able to stack them as close as you can now so I would have to increase explosion size, seems more work than just shrinking one unit size down

**Comment by skymyj** [comment]
Is it possible to have a design for each level ?

**Comment by SoulRaiZor** [comment]
Would be awesome if its design is getting closer to  t4 design with increasing number

**Comment by nixtux** [comment]
pushed different fix for now  https://github.com/n3wm1nd/TA/commit/5b5a0dd30b29c48287815fb0f6d3a943a43df423
