### ISSUE TITLE
T1.5 Core mex doesnt stop working if metal bar is full

### ISSUE THREAD

**Issue by SoulRaiZor** [n3wm1nd/TA#570]
Hey it keeps draining e for no reason.
And it takes 50 e to run.
T2 mex just 25

**Comment by nixtux** [comment]
do any mexs ?

**Comment by SoulRaiZor** [comment]
Oh i thought so :-D

**Comment by SoulRaiZor** [comment]
I will check if i can make a widget.
I just need access to metalbar of whole team

**Comment by nixtux** [comment]
soul just use Spring.GetTeamResources you can get both income and storage

**Comment by SoulRaiZor** [comment]
Ya i will try. Thx

**Comment by SoulRaiZor** [comment]
Ok, i found a problem.
Turning off corexp and cormexp also stopps them from shooting.
Dont know how we can fix that.

1. I can check every unit in LOS if its near mex and then turn on (needs lots of calculation)
2. I can exclude those mexes
3. U got some better idea :D

**Comment by nixtux** [comment]
Imo you need to check all ally team as If your excessive it means free metal for other team mates, otherwise it pointless as metal > energy

**Comment by SoulRaiZor** [comment]
of course

**Comment by SoulRaiZor** [comment]
I just exclude them now.
Should be finished on we.

**Comment by nixtux** [comment]
Going to close issue as can be fixed user side
