### ISSUE TITLE
Nuke rework

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#571]
So this will replace the currents system with fast nukes, and replace with hipower nukes and rework antis into long range antis

current changeset for arm faction https://gist.github.com/nixtux/c6f849a399c25b88a5a5

thoughts please

**Comment by nixtux** [comment]
Current planed change set for all factions 
https://gist.github.com/nixtux/63b54e3d12921973ce38 https://gist.github.com/nixtux/941230a242832c59f2c3 https://gist.github.com/nixtux/6b4300ceab90a5ae663a

**Comment by skymyj** [comment]
I tested & it's good for me. 
Just antinuke mobile : why they produce +200ke/s & structures nothing ??

**Comment by nixtux** [comment]
there hybrid kbots :D, wont change
