### ISSUE TITLE
Bantha Canon range to increase

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#572]
![bantha canon](https://cloud.githubusercontent.com/assets/2990630/6091755/9a52f95a-aebb-11e4-94c0-806eeaaba80c.png)

**Comment by SoulRaiZor** [comment]
hmm i compared him to jaguar.
Bantha isnt that bad from stats, but the starbust launcher isnt working for me?
can u confirm that?

But iam fine with increased range of cannon.
Maybe ~500?
