### ISSUE TITLE
Terroriser

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#580]
Terroriser is never played. 
![tawf014](https://cloud.githubusercontent.com/assets/2990630/6460131/f3e1b696-c194-11e4-8da6-f909c4c25bfc.png)

First Cause : It requires advanced t2 unit research centre. If you make T2 Tech, Tankanator is better choice.
Second : It's a long range unit & Penetrator (T2) have already this function. For Core, Banisher is the only long range with high damage.

I suggest 2 differents strategies for this unit : 
- Don't change anything, except delete the Required Tech 2 center.
- Adopt an artillery strategy like catapult with only 1 rocket unguided : 

![armraven](https://cloud.githubusercontent.com/assets/2990630/6460173/38e6044a-c195-11e4-956d-8575347fbbdc.png)

:+1: Advantage : Better range than tankanator.
Stats : 
1900 dmg / rocket
Aoe : 100
Range : same than Totalitarian : 1850
Rocket : unguided
7s for reload
Metal Cost :  2100
Energy Cost : 20000
Buildtime : 9000
HitPoints :  1950
Movement : Same than actually. 
Requires advanced t2 unit research 
Don't change visual effect & curve.
Like : http://en.wikipedia.org/wiki/Katyusha_rocket_launcher

**Comment by nixtux** [comment]
Fix but with terroriser missile falling short of target

**Comment by nixtux** [comment]
found a unit to replace terroriser

**Comment by nixtux** [comment]
Closing replace unit with new unit horge

**Comment by skymyj** [comment]
Is it effective on release to test it ?
