### ISSUE TITLE
AntiNuke Cost Balance

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#582]
I see on antinuke : > -11km/s vs -1.8km/s for mobile antinuke
Is it possible to decrease cost for structure & increase for mobile?
Like 4km/s for mobile & 6km for structure
I have other proposition too : stockpile = 0 for mobile antinuke

**Comment by nixtux** [comment]
I wont decrease cost for structure's but i will remove the extra energy produced by mobile antis (i will inverted the energyMake) so now mobile cost energy when not producing missiles

**Comment by skymyj** [comment]
So is it possible to make 0 missile in queue after make building. 
& increase cost e/s & m/s for adv antinuke mobile ?

**Comment by skymyj** [comment]
Ok. But it's no logic than they cost energy if no production or services.. 

So is it possible to make 0 missile in queue after make AntiNuke mobile.
& increase cost e/s & m/s for adv antinuke mobile ?

**Comment by nixtux** [comment]
Pointless to make no missile in queue as could be overridden by lua widget

**Comment by skymyj** [comment]
Ok. But for all my game, If I choose Core. I will have vehicule + Adv Fusion & cheap Mobile antinuke. Good advantage.
