### ISSUE TITLE
!ring or new !pmring command to send PMs

### ISSUE THREAD

**Issue by Bla1** [n3wm1nd/TA#583]
Most people use springlobby, and new springlobbies generally don't do anything when the !ring command is passed. I remember times when we were waiting for unready players, and we tried ringing them many times to no avail, but after sending them 1 private message to ready up, they become ready.

There should be a new command or change old !ring command so the player gets a private message to ready up.

**Comment by nixtux** [comment]
Won't do anyone about this not mod problem
