### ISSUE TITLE
Technology Tree

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#584]
Some suggestions for Star Commander Balance.

- Is it possible to delete pwee / AK canon. Not enough range and maybe too fun & discredit TA.

- Is it possible to delete Hardened  Nano form T2 Nano Morphing panel ? Actually, Players have no knowledge on the difference between hardener & T3 Nano. The fog.

![ananotower](https://cloud.githubusercontent.com/assets/2990630/6556353/234eb546-c66d-11e4-9467-666834c26211.png) ![cnanotower](https://cloud.githubusercontent.com/assets/2990630/6556351/2219550a-c66d-11e4-9113-ce9db5470d54.png) 

Add Hardened Nano to the star commander. 
This Nano will cost 5000~10000Km. Limited to 1. 
With long range radius (like T4) & good Build Speed (1800).

This Nano could construct All Morphed structure units like  Nuke T2.5, Antinuke T2.5, Vulcan T2.5, T2.5 Bertha, Plasma deflector T2.5 & T3.5 Shield Kbot (not limited to 1)
![armpraet](https://cloud.githubusercontent.com/assets/2990630/6616299/df5dd032-c8ac-11e4-980b-466cad8f4995.png) ![armbrtha](https://cloud.githubusercontent.com/assets/2990630/6616328/29522b84-c8ad-11e4-82a4-073874d01a84.png) ![armanni](https://cloud.githubusercontent.com/assets/2990630/6616329/29607c8e-c8ad-11e4-8bb8-33660cd68f6e.png)

For assaut commander, the combat engenereer could make T2 morphed unit : Goliath, FatBoy, Sumo, Demon. (unlock with Assault commander)
![armfark](https://cloud.githubusercontent.com/assets/2990630/6616304/f0d31610-c8ac-11e4-96e4-5212eca1b7cc.png)

![corgol1](https://cloud.githubusercontent.com/assets/2990630/6556350/21f2e2f8-c66d-11e4-99eb-0c2f059187f5.png)

For TLL Star Commander, don't change. Just balance irritator (too strong)
=> decrease Shield & Damage. (Same for Arm & Core Shield unit). 

for Moonkey, can we have  more precision on damage / second ?

**Comment by skymyj** [comment]
![capture01](https://cloud.githubusercontent.com/assets/2990630/6616251/7dacaeda-c8ac-11e4-95b7-69891e5775f6.PNG)

Just add T3 constructor for Supreme commander. 
Actually, If you choose supreme commander, you don't have access to all structure T4. And you can't spend for T4 Tech center. Too much resources to have Commander & T4 Tech center.

**Comment by skymyj** [comment]
Capture with more details. So Nixtux, what do you think about ?
![capture01](https://cloud.githubusercontent.com/assets/2990630/7043806/32ab116e-dded-11e4-8a93-6ad3007d8269.PNG)

**Comment by konecat** [comment]
Reverse the change. It's bullshit.

No one will morph the T4 RC anymore because it's useless if you can get cruiser by morphing anyway.

Morphed T2 units SHOULD NOT BE possible to build outright. They're too overpowered to be allowed to be built. Leave it as it was.

**Comment by skymyj** [comment]
All can change Konecat. It's just a project & I'd like to test to know if it's balanced or not.
But no way to panic. The assault commander will stay to 8000KM.
My goal is to choose between commanders way or Tech Center way. (actually, you can't spent 60000Km more if you want a T3 Constructor cruiser). Each of these ways give some advantages. 
For morphed T2 unit, there is nothing done.
For morphed T3 units, you have to build a hardener nano (cost 14K & 200000KE). The cost is the same than a T3 Lab. I think, there is more balance now. You have to spend 14km before make a shield bot. Before it was too unbalanced with these Shield Kbot. No change for TLL, but the cost will be increase & Strenght decrease for irritator. Moreover the Nano can't move & it's range limited to 800~1000. So, all the structures except Shield Bot have to stay near the Nano.

**Comment by konecat** [comment]
> I'd like to test to know if it's balanced or not.

I assure you it's not. I mean come on. Just look at it. IMO what I propose is much more save.

**Comment by skymyj** [comment]
Konecat, thanks you for you propose. 
Can you say me if it's that ?
![capture konecat](https://cloud.githubusercontent.com/assets/2990630/8454050/99c417f2-1ffa-11e5-9948-6588e24a3b3c.JPG)

**Comment by konecat** [comment]
Hmmm. We lack a middle ground between a Star commander and Supreme. 

I say we do it like this:
Make Tech center lvl3 back to 60km.
Move Hardener Nano to Star Commander. Hardener Nano(pump its health to at least 10k HP)= ~22km
Move T4 Lab to Supreme commander (basically leave Supreme Commander in its old state).

Now that I think about it, no one will use Hardener nano if you need Supreme com for that. Tech center much better choice (T4 eco). 

We'll see how it works.

**Comment by skymyj** [comment]
My propose was dated from the 8 avril. I had news idea but the main idea is the same.
I just want a T4 Combat/Tech Commanders to balance with Tech Center. With lock Vulcain & TSAR & HERO LAB, I think we have a compromise.
![capture skymyj](https://cloud.githubusercontent.com/assets/2990630/8454141/63ade660-1ffb-11e5-9925-6dc4b1b3f93f.JPG)

**Comment by konecat** [comment]
I don't want cruiser to be unlocked by commander. Even if you lock hero factory, I'd go for commander upgrades anytime. T4 eco is very precious. I vote for leaving T4 eco pathway as it was.

I will agree almost to any modifications you want to make to commander, but not a damn cruiser.

**Comment by skymyj** [comment]
I think, we have to wait Keijjii, Solv, Nixtux, Finkky & other oppinions.

**Comment by negrojew** [comment]
I think that before trying to change endgame mechanics, the early/mid game balance comes first.

Not only does your proposition ignores this, but it furthers one of the major flaw of early game: the battle commander is just too poor of a choice compared to the eco commander.
Which just makes tech center fairly underwhelming in comparison. Let's face it, kbot start is what is being used 90% of the time; going veh/TC or going battle com is just way too situational to have any use.
What you're asking for will just futher that gap.
You should just ask for the TC to be removed if you hate it so much.

**Comment by skymyj** [comment]
> You should just ask for the TC to be removed if you hate it so much

I Like it. I often use TC on my games. But I'm ok with you & Konecat. Commanders coud not make T3 Cons. 
Just  T4 Lab as before. 

Maybe Add a T3 Antinuke.
