### ISSUE TITLE
[BUG] Banshee stuck on LLT

### ISSUE THREAD

**Issue by DeathStarSPRING** [n3wm1nd/TA#585]
Banshee (Arm t1 Air unit) stuck on light laser tower (LLT).
There are 2 screenshots for your convenience:
http://imgur.com/OO41e9Y,NUxyoHn#0
http://imgur.com/OO41e9Y,NUxyoHn#1

Please address this issue.  Thank you.

**Comment by nixtux** [comment]
Cant reproduce in latest engine (102), closing issue
