### ISSUE TITLE
Discharge - JetPack Kbot Balance

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#587]
Is it possible to increase range for primary weapon ? 
Actually, they EMP target, but to kill it, they have to come closer & they will be kill.

Fix Range to 400 & +10% DPS.

![tlldischarge](https://cloud.githubusercontent.com/assets/2990630/6731098/7cfd6718-ce42-11e4-80b6-90a460e5c235.png)

**Comment by nixtux** [comment]
no change needed here imo
