### ISSUE TITLE
combat com buffs

### ISSUE THREAD

**Issue by Bla1** [n3wm1nd/TA#592]
The eco com can build pocket fusions and adv metal makers, but the combat com can't make anything above t1. I think the combat com should be able to make adv llts and boosted defenders, to balance the eco com's t1.5 options.

**Comment by skymyj** [comment]
I agree. Actually, it's assault com that can make boosted aadefenders & (double llt or blue llt).

What do you think about this: https://github.com/n3wm1nd/TA/issues/584

**Comment by Bla1** [comment]
I agree with most of the thing you mentioned in #584. I think ak/peewee/private cannon should stay though, its quite cool. Maybe allow it to be morphed with a t2.5 rc so it can fire once a second or something really fast. Other than that, I agree with everything.
