### ISSUE TITLE
Air transport Strategy

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#600]
I played yesterday with air transport strategy. 
I could transport SUMO with T1 air... So, what is the interest of T1.5, T2 & T3 Air transport.

Is it possible to determine : 

T1 Transport : For T1 & T1.5 Unit & light T2 Units. (Until 2.5K HP)
T1.5 Transport : For Commander & medium T2 Units (until 5K HP)
T2 Transport : For T2 & T2.5 & light T3 Units (until 20K HP) (except Krogtsarr & Vengence)
T3 Transport : For T3 & T3.5 Units (until 70K HP)

=> T3 Transport are never used. And If you use them, you can't transport a Bantha unit... Ok to not transport Fury, Krogoth or Juggernaut. 

Until 70-90K HP should be transported.

**Comment by nixtux** [comment]
Can't do lock via hp without loads of work, engine only support footprintsize and mass as limits for transports

**Comment by skymyj** [comment]
Hmm. I'm not sure to understand all.. 
For T3 transport, is it possible to pass over engine & accept some T3 units like T3 bantha, , T3 flammer..

**Comment by skymyj** [comment]
If you can't. You could delete T1.5 & T3 unit to decrease units.

**Comment by nixtux** [comment]
As I said it first post it can be done but it's a bit of work, as unit mass is hard to change with undesirable effects, and no I won't be deleting them
