### ISSUE TITLE
M270 MLRS balance

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#606]
This new unit is not balanced. 
Is it possible to make same stats than older ? 

(I prefer the old launcher design. This unit looks like a t2.5 unit... tankanator is most impressive)

**Comment by nixtux** [comment]
Explain why you think it not balance it same stats as before just damage and reload time changes so has same dps as before

**Comment by nixtux** [comment]
And model was changes due to texture bug in old model

**Comment by skymyj** [comment]
Ok for model... 
- 200 DPS forT3.5 unit.. Maybe fix to 280 like Howie (T3.5 Core Kbot) & increase a little (+300) his metal cost.
- Increase his speed (like Howie) => you can't play a strategic war with this unit that can't retreat

**Comment by skymyj** [comment]
Can we add a fire effect on rockets ?

**Comment by skymyj** [comment]
Did you procedd to change on github ?
I saw 3 burst of 2000 damage with 360 AOE ?
