### ISSUE TITLE
KrogCrush weapon

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#607]
What is this weapon ? I never saw it in action.
If no used, is it possible to delete from description weapon.

Weapon Name : KrogCrush
Range 	Aoe 	Reload 	Burst 	Projectiles
125 	62.5 	0.10 	1 	1
Armor Class 	Damage 	Dps
Default 	500 	5000
Subs 	5 	50

**Comment by nixtux** [comment]
It's used krog does damage with foot to ground units when close

**Comment by skymyj** [comment]
hmm ok but 5000 DPS ?? * 2 = 10000 DPS ??

Can you delete one KrogCrush from stats ?

**Comment by nixtux** [comment]
No, it's 1 weapon per foot, so x2 in stats is fine

**Comment by skymyj** [comment]
So why for super krogoth T4, there is only 1 weapon KrogCrush ?

**Comment by nixtux** [comment]
Checked looks like superkrog one is old/broken will fix
