### ISSUE TITLE
Where or where is that sniper shooting from

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#614]
Idea, add a 2nd fake beam laser which does no damage, ie it just to show where snipers are shooting from, it should only be visible while other weapon is aiming(needs to be a slave to weapon) 

Feedback please

**Comment by skymyj** [comment]
I think it's a good idea. I like this. 
You could add : snippers can't shoot over units.

**Comment by nixtux** [comment]
Ok pushed a change here but you get a invisible laser all you will see if that your units is being aimed at, ie a red dot pinned on your unit like in the movies :), please test want todo a release soon

**Comment by skymyj** [comment]
Cool :) I will tomorrow

**Comment by skymyj** [comment]
I tested. The concept is really good. 
But If possible, I d like to test with no invisible beam laser. I think, we could take a red beam laser with alpha to 50%. 
Visible or invisible, is it possible to make 0 damage / second ?

**Comment by skymyj** [comment]
For Corprot, laser range 1100. Is it possible to make at 1050 as main weapon range.

**Comment by nixtux** [comment]
Hmm should already be no damage per sec, I could make it a mod option default not visible

**Comment by skymyj** [comment]
Actually 1 damage & 0.1 for reload. total 10 damage by second.

**Comment by nixtux** [comment]
I don't want it to make damage, would be too much like a laser and could confuse players, the idea is so players realise there under attack from a sniper adding damage and laser beam would be counter productive imo

**Comment by skymyj** [comment]
Work for me. I hope this evenning I could test in real game.
