### ISSUE TITLE
Terramorphing Rules

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#615]
Is it possible to unlock this feature when you construct a Tech Center or when you morph in battle com. (or assault com if you chose eco com first). 

I saw many constructors & nano with terraforming options, it's cool. But if you have to morph in assault com, you reduce use of this awesome feature.

**Comment by nixtux** [comment]
Hmm odd, it should only unlock the teraforming button for commanders and combat cons for arm/core or t2 cons for tll, if not this is a bug

**Comment by skymyj** [comment]
All vehicules have it :)

**Comment by skymyj** [comment]
You should let this feature for all Nano
