### ISSUE TITLE
Plasma Shield bug

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#616]
Yesterday, I saw a Plasma shield with 20% HP et 90% loaded be killed by artillery plasma that pass it.
(artillery plasma was T3.5 ship)

So my question : Does Plasma shield must have 100% life et > 20% to counter plasma shots ?

**Comment by nixtux** [comment]
Need unitname for shield and boat, if DAMAGE > Shield hp (not unit hp)  then projectile will pass thought

**Comment by skymyj** [comment]
Was Triumph vs Keeper. 
Unit hp was 20% & shield HP 90%.

**Comment by skymyj** [comment]
Tested & work
