### ISSUE TITLE
Bug: metal maker stop work after take/send abandone units

### ISSUE THREAD

**Issue by playerO1** [n3wm1nd/TA#617]
The metal maker stop work when energy enough - over 99%. After the crash I see that Tech Annihilation metal maker widget can lost from screen.
How to reproduce bug:
In team game, where one of team left, press big blink button "take abandoned units" for take all unit of left player. Where player come back, take (share) unit with metal makers to him back.
After this moment all my metal makers stop work. If I share no working metal maker to other player - they start work. Where I build or capture new metal makers - they stop work again. Sometime same of metal maker start work randomly, but not all and no long time.

**Comment by nixtux** [comment]
Pushed fix but needs testing

**Comment by nixtux** [comment]
Closing
