### ISSUE TITLE
Coradon (skymyj) 

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#636]
float beamTime Default: 1.0  
How long in seconds to fire the laser before waiting for reloadTime to start. Damage is distributed over the duration of the beamTime, and the weapon will aim to hit the target when the beam is in the middle of its beamTime (i.e. using prediction).

**Comment by skymyj** [comment]
On stats, I saw : 
- duration = 10,
- beamWeapon = true,
- burnblow = true,

versus for Mobile Tachion
- beamTime = 0.3,
- beamlaser = 1,

**Comment by skymyj** [comment]
Maybe, we transform beamweapon into beamlaser (same than tachion). 
I think, Adonis reload is too long. We need 5.5 second as Mobile Tachion. (if we can adjust damage to 2650)

**Comment by skymyj** [comment]
Did you have a file with all variables decriptions ?

**Comment by nixtux** [comment]
https://springrts.com/wiki/Gamedev:WeaponDefs
https://springrts.com/wiki/Engine_Development

But yeah changes it to beam laser, just copy paste

**Comment by nixtux** [comment]
I've replaced coradon weapon with a beam laser type weapon (with nicer effect)  it may need a little balance tweaking

**Comment by skymyj** [comment]
So, now damage is really 2650 per shot ?

**Comment by skymyj** [comment]
I think it's a good balance for a T2.5 unit. 
Maybe increase a little cost.

**Comment by skymyj** [comment]
Nix, they can't shoot over wreckage. Is it possible to fix it ?

**Comment by nixtux** [comment]
laser or rocket ?

**Comment by skymyj** [comment]
I dont remember.. 
I will test this evening.

**Comment by skymyj** [comment]
It works.. 

But they can pass over teeth T1. 
Is it possible to fix it for coradon & armtem ? (with ground & sea teeth ?)

**Comment by nixtux** [comment]
Closing as teeth issue is same as #857
