### ISSUE TITLE
Howie

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#643]
Is it possible to have a random trajectory for the 4 missiles ? 
https://github.com/n3wm1nd/TA/blob/master/units/corhowie.lua

**Comment by skymyj** [comment]
I tested it yesterday but I didn't saw changes.

**Comment by nixtux** [comment]
Try again now I've pushed a fix for this

**Comment by skymyj** [comment]
It works :) 
What did you change for this result ?
