### ISSUE TITLE
Bantha ImpulsionBlaster

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#658]
On lua file, range = 500
But in game, it's like 100~200
Don't understand. Can you explain ? 

Idea : remplace plasma gun from Jaguard (Bantha All terrain) by this weapon

**Comment by nixtux** [comment]
Did you change range?, velocity is too low but you can't change it, it's set low for weapon effect visuals

**Comment by skymyj** [comment]
No, i didn't change range. Ok for the visual effects

**Comment by skymyj** [comment]
Same for gorilla. Canon range is 750 with 350 range in fact
