### ISSUE TITLE
Advanced Gunship - Anti T3/T4

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#687]
Is it possible to add other visual effect for ARM/CORE T3 AIR.

ARM : Same weapon than HellDriver / Brawler.
CORE : Same weapon than Blade (just have more velocity)

If you are ok with that, I will make changes this afternoon.

**Comment by nixtux** [comment]
Iirc they have 2 weapons, you on about the to ground weapon?

**Comment by skymyj** [comment]
Hum, I spoke about : 
- Perseus : https://github.com/n3wm1nd/TA/wiki/armpers
- BlackDawn : https://github.com/n3wm1nd/TA/wiki/blackdawn

& I propose to delete : 
- Dragona : https://github.com/n3wm1nd/TA/wiki/corrag
- Liberty : https://github.com/n3wm1nd/TA/wiki/tawf015

=> Cause, they are never used. At T3, players need T3 Fighter, Or Anti T3/T4 Or bombers. These units are not very efficient for air or for ground.

**Comment by nixtux** [comment]
Hmm delete units?, it's a shame liberty is a nicer looking unit imo than blackdawn

**Comment by nixtux** [comment]
Do it and when I get free time I will swap the models around
