### ISSUE TITLE
Delete Mortar

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#690]
Is it possible to deleted these structures unused. For Arm/Core. 

We could add a morph for T1 plasma canon into T2 canon.

https://github.com/n3wm1nd/TA/wiki/amortor

**Comment by nixtux** [comment]
No they are used imo, me for one uses them

**Comment by skymyj** [comment]
hmm, ok, but I think imho, it will be better after have made a canon plasma, you could morph into T2 canon plasma with more range & damage. 
We could have less units for more balance & it will be easy to play.

**Comment by skymyj** [comment]
you will use T1 plasma canon more if you can morph after in T2.

**Comment by nixtux** [comment]
Ok do it
