### ISSUE TITLE
Restore Button - terramorphing

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#699]
Actually, we have 2 buttons for the same feature... 

Is it possible to delete one of them  ? 

I'd like we keep the new restore button. When you can select zone with precision.
This button have to use for all cons/rez unit.

**Comment by Zonkspring** [comment]
I agree so very much... old restore button is kinda meh, tiny radius, fake circle (in reality it restores a quadratic space). 
New restore however is awesome, just like the rest of terraforming.
