### ISSUE TITLE
Anti Air Defaut damage

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#710]
Nixtux, 

Defaut damage is it an obligation ? 
Cause on stats (space bar on unit), we see 5 damage.. I had never understand why... until today when I saw stats on unit files.

Is it possible to delete defaut damage ? 
If not, is it possible to fix more damage ? (ex : bomber = 750, fighter = 750, unclassed air = 600, defaut = 600)  => defaut = unclassed damage for more visibility ???

**Comment by skymyj** [comment]
Is it possible to clean all weapon from Kbot T2 AA ?? 
10 weapons :X

**Comment by nixtux** [comment]
No can't be changes on both counts
