### ISSUE TITLE
Armorco bug

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#714]
The blue laser actually miss all target. I try to fix, but I fail..
Can you see this ? thanks

**Comment by skymyj** [comment]
Same for hyperion unit. 
They can't middle their shots

**Comment by nixtux** [comment]
Is this with spring 98 or host with test engine?

**Comment by skymyj** [comment]
98.0.1-704 (test engine)

**Comment by skymyj** [comment]
Better in 98.0 :)

**Comment by nixtux** [comment]
Ok cool, well less retest later with current engine git and report issue if it's not already fixed

**Comment by skymyj** [comment]
Roger !
