### ISSUE TITLE
Vehicle T3 All Terrain

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#720]
Is it possible to transform them into Ship & Ground Unit ? 
Not Hover, not amphibious... Same than Pelican.

Actually, there is no All Terrain Vehicle in T1 T2.

**Comment by nixtux** [comment]
It would look stupid imo can't see why they would float

**Comment by skymyj** [comment]
Hmm. & If we change strategy. Delete the All terrain feature & increase velocity ? 
"Fast Assault vehicle" in description unit.

**Comment by nixtux** [comment]
Then there would be no countpart to all terrain t3 kbots

**Comment by skymyj** [comment]
There is already no countpart for Spider & T2.5 Kbot.

**Comment by skymyj** [comment]
The strategy coud be make AA to counter All terrai, Nuke...

**Comment by skymyj** [comment]
Do you know the variable for set All terrain or not ?
thanks

**Comment by nixtux** [comment]
I do :)

**Comment by nixtux** [comment]
So you need to change movement class, check /gamedata/movedefs.lua, just pick one that is used by another units that can do what you need, but make sure it matches unit footprint or there will be pathing problems, also don't add any new movedefs if there is one you don't have its too costly

**Comment by nixtux** [comment]
Also http://www.collinsdictionary.com/dictionary/english/all-terrain   :P

**Comment by skymyj** [comment]
yeah :) maybe change the desription ? Climb kbot ?

**Comment by nixtux** [comment]
Nope it is fine
