### ISSUE TITLE
Juggernaut & Juggernault

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#722]
2 units share the same name. (except the "L")
Is it possible to change name for one of them ?

**Comment by Zonkspring** [comment]
I think Juggernault should be the one to change name? 
Core Juggernaut exists since far longer time, it has older rights. :) 
Name Suggestion: Boreas (Greek god of north wind, tho the name also meant "Devouring one")
https://en.wikipedia.org/wiki/Anemoi#Boreas

**Comment by skymyj** [comment]
+1 like
