### ISSUE TITLE
Anti Canon T3/T4 (Nebrasca & butcher)

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#724]
Please, is it possible to unlock them with t4 & Add on T4 construction ship.
Delete from engeneerer & T2 constructor.

Can i do it ?

**Comment by skymyj** [comment]
Nix, what is your mind on this topic ?

**Comment by nixtux** [comment]
Anti t3/4 should be available in lower tech level otherwise imo it make them pointless
