### ISSUE TITLE
Revert all the menu changes

### ISSUE THREAD

**Issue by konecat** [n3wm1nd/TA#740]
corack and armack (T2 builders); all T3 labs of ARM&core factions (also veh/air builders etc.)

A lot of players are used to the old ones and the new ones lack a lot of things that were previously available. Changes nowhere to be found in changelogs.

**Comment by skymyj** [comment]
Actually, changelogs are not update. 
It will be find soon.
- engineerer can construct all defense weapon structure 
- Adv Cons can construct all Adv Structure & Lab (exception : Experimental Canon)
Goal : Have less unit in menu panel.

**Comment by konecat** [comment]
No. I do not agree to this change, nor anyone else did. It's not a good idea. Nix comment on this.

**Comment by skymyj** [comment]
Why nix merges your shit? Is this some kind of conspiracy? => I don't know. I just proposed.
Can you explain me why it's a bad idea ? thanks

**Comment by konecat** [comment]
Hmmm I don't know. Maybe because it was that way for over a year now, it worked very well, every player got used to the menu and you just removed & changed half of them?

**Comment by skymyj** [comment]
I know it's more difficult  to search all structures in panel menu, but finally, it will be easier imho on long-term. After 2-3 weeks, you will not search for this or this structure.
Actually, when you take Kbot Cons : the t3 lab is in third position. If you take Air Cons, the air lab is in last position. We need a clean & I take this opportunity to go further.

**Comment by konecat** [comment]
It's not up to you to decide. That's one. Second, there's a lot of structures missing, they build less things. Why would you even change all that without consultation with other people?

**Comment by skymyj** [comment]
If I take your example, T3 cons build less thing than T1 cons... 
We need to see if these things had a real interest for this Adv cons ? Actually not, cause you can construct these structures with the combat  enginireer.
& All things/updates done can be edited again. It's my changes that make we have a discussion & add ideas. I think it's the "construtivism".

**Comment by skymyj** [comment]
Don't see this like a conspiracy. If players think it's bad, we will change this. It's the advantage to play with an open source game.

**Comment by konecat** [comment]
>If I take your example, T3 cons build less thing than T1 cons... 
What that has to do with anything I said? I can't even understand half of the things you say anymore.
No idea what your post was about. Be more clear.

Problem is the change itself. I will apply bullshit patches then, if you think open source game is an excuse to completely change system "because you feel like it".

**Comment by skymyj** [comment]
> It's not up to you to decide. That's one. Second, there's a lot of structures missing, they build less things. 
> ... If I take your example, T3 cons build less thing than T1 cons... 
I would say, number of units for T1 constructor is bigger than T3 constructor cruiser. 
Number of units is not a key to determine the unit performance in the game. 
& sorry for my bad english..
