### ISSUE TITLE
tlllmt morphing

### ISSUE THREAD

**Issue by konecat** [n3wm1nd/TA#741]
Allow morph without experience (like cor&arm)

**Comment by skymyj** [comment]
Indeed, we have changed the morphing rules. 
Now, AA need 0.01 xp (like pewee/AK). Need 1-2 shots to morph.
Same for TLL.

**Comment by konecat** [comment]
No.

**Comment by skymyj** [comment]
Same for Rapid Bomb resistant.

**Comment by skymyj** [comment]
For your information
