### ISSUE TITLE
Distance Build for Adv Constructor

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#744]
I propose to increase Distance Build (fixed to 150) to 300 (same than Adv sub). 
It will be easier to build for example AdvFusion in chain withouth be blocked by helper units.

What do you think about this ?

**Comment by konecat** [comment]
It will promote simcity gameplay and lack of micro management. I vote no

**Comment by negrojew** [comment]
I don't think making building in chain as the only factor would justify doubling a distance build; you should substantiate a little more before proposing stuff.

**Comment by skymyj** [comment]
These units will construct to 225 range now vs 155. 
The Vehicle made hard the T3 LAB.
& Like commanders & Nano, the tech level will determine the distance build increase.
