### ISSUE TITLE
Morphing Flak

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#745]
Like Annihilator & Doomsday, I'd like propose a morphing option for Flak structure with a higher xp (like 1.5 or more).

**Comment by konecat** [comment]
You mean like T2.5 flak upgrade? If it's at least 1.00XP then I agree if it isn't too OP.

**Comment by skymyj** [comment]
Sure 1.00 or more. I will test it.

**Comment by konecat** [comment]
Cool it's closed but just to be clear - don't make it morph into a T3 structure.

Just make it "reinforced flak" and change its texture or something along that.
