### ISSUE TITLE
Anti Nuke loaded with 1 missile

### ISSUE THREAD

**Issue by h4nn3ss** [n3wm1nd/TA#748]
Anti Nuke is loaded with 1 missile when finished building.

**Comment by skymyj** [comment]
I think you are right. 
I vote for 0 missile in queue for all anti-nuke. (actually, T3 anti-nuke have 0 amunition)
Or : 
Mobile Anti Nuke => 0
Structure (they cost more) Anti Nuke => 1

**Comment by konecat** [comment]
All it will do is promote nuke rush. 

>Mobile Anti Nuke => 0
>Structure (they cost more) Anti Nuke => 1

Is what it should remain at

**Comment by skymyj** [comment]
+1 with konecat

**Comment by skymyj** [comment]
Same for T3 Anti Nuke ? 1 ammunition ?
