### ISSUE TITLE
Underwater MOHO Extractors and subs killed by Bertha , Behemoth etc..

### ISSUE THREAD

**Issue by h4nn3ss** [n3wm1nd/TA#749]
Underwater MOHO Extractors and subs killed by Bertha , Behemoth etc..

**Comment by skymyj** [comment]
I confirm for Moho extractor & for many other underwater structures

**Comment by skymyj** [comment]
Hover can kill sub extractor now...

**Comment by nixtux** [comment]
The problem is there aoe is too large, Fix would be reduce aoe by half

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/commit/f31ef86e6858c2c31b4a9684a65fabe2d015b2f8
