### ISSUE TITLE
For finkky's eyes only

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#755]
Slow update rate has changed to 15 now not 16 like before, so how did you work out this magic number :)   https://github.com/n3wm1nd/TA/blob/master/luarules/gadgets/game_energy_conversion.lua#L56

**Comment by Finkky** [comment]
I dont know what you exactly mean by slow update rate but 
something with 16 and refresh rate is on this line:
https://github.com/n3wm1nd/TA/blob/master/luarules/gadgets/game_energy_conversion.lua#L32
