### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by nixtux** [n3wm1nd/TA#757]
spirng is nice now and warns of deprecated tags, ive done the mass cleaning just the last few ones todo manualy there more typos than dead tags

[f=0000000] Warning: WeaponDefs: Unknown tag "balistic" in "akmech_akmech_rocket"
[f=0000000] Warning: WeaponDefs: Unknown tag "targetmoveerrorr" in "anvil_anchorempbeam"
[f=0000000] Warning: WeaponDefs: Unknown tag "aimrate" in "arm_berthacannonemp1"
[f=0000000] Warning: WeaponDefs: Unknown tag "color" in "arm_berthacannonemp1"
[f=0000000] Warning: WeaponDefs: Unknown tag "holdtime" in "arm_berthacannonemp1"
[f=0000000] Warning: WeaponDefs: Unknown tag "rendertype" in "arm_berthacannonemp1"
[f=0000000] Warning: WeaponDefs: Unknown tag "soundwater" in "armcybr_arm_pidr"
[f=0000000] Warning: WeaponDefs: Unknown tag "balistic" in "armcyclone_mk-83"
[f=0000000] Warning: WeaponDefs: Unknown tag "burts" in "armcyclone_mk-83"
[f=0000000] Warning: WeaponDefs: Unknown tag "cruisealt" in "armcyclone_mk-83"
[f=0000000] Warning: WeaponDefs: Unknown tag "flighttimer" in "armjeth_armkbot_missile"
[f=0000000] Warning: WeaponDefs: Unknown tag "soundwater" in "armmech_armmech_cannon"
[f=0000000] Warning: WeaponDefs: Unknown tag "cruisealt" in "armmlrs_barrage"
[f=0000000] Warning: WeaponDefs: Unknown tag "impulserboost" in "armpaspd_armpaspd"
[f=0000000] Warning: WeaponDefs: Unknown tag "impulserfactor" in "armpaspd_armpaspd"
[f=0000000] Warning: WeaponDefs: Unknown tag "flighttimer" in "armpt_armkbot_missile"
[f=0000000] Warning: WeaponDefs: Unknown tag "--falloffrate" in "armraz_mech_rapidlaser"
[f=0000000] Warning: WeaponDefs: Unknown tag "bursrate" in "armrl1_armrl_missile1"
[f=0000000] Warning: Could not load sound from def: null
[f=0000000] Warning: WeaponDefs: Unknown tag "comandfire" in "armtabi_arm_tabithacannon"
[f=0000000] Warning: WeaponDefs: Unknown tag "btracks" in "cdevastator_devastatorrockets"
[f=0000000] Warning: WeaponDefs: Unknown tag "edgeofeffectiveness" in "cdevastator_devastatorrockets"
[f=0000000] Warning: WeaponDefs: Unknown tag "targetmoveerrorr" in "cdevastator_mountedantimatteraccelerator"
[f=0000000] Warning: WeaponDefs: Unknown tag "targetmoveerro" in "corcrab_core_lightlaser2"
[f=0000000] Warning: WeaponDefs: Unknown tag "flighttimer" in "corcrash_corekbot_missile"
[f=0000000] Warning: WeaponDefs: Unknown tag "balistic" in "coreclipse_fab500"
[f=0000000] Warning: WeaponDefs: Unknown tag "cruisealt" in "coreclipse_fab500"
[f=0000000] Warning: WeaponDefs: Unknown tag "comandfire" in "corflu_cor_flucannon"
[f=0000000] Warning: WeaponDefs: Unknown tag "corethinkness" in "corgfbt_fireball"
[f=0000000] Warning: WeaponDefs: Unknown tag "soundwater" in "corgfbt_fireball"
[f=0000000] Warning: WeaponDefs: Unknown tag "dropped" in "corgripn_bomb"
[f=0000000] Warning: WeaponDefs: Unknown tag "cruisealt" in "corhowie_asm"
[f=0000000] Warning: WeaponDefs: Unknown tag "soundwater" in "corkarg1_super_missile1"
[f=0000000] Warning: WeaponDefs: Unknown tag "soundwater" in "corkarg_super_missile"
[f=0000000] Warning: Could not load sound from def: null
[f=0000000] Warning: WeaponDefs: Unknown tag "flighttimer" in "corpt_armkbot_missile"
[f=0000000] Warning: WeaponDefs: Unknown tag "targetmoveerro" in "gladiator_gladiator_laser"
[f=0000000] Warning: WeaponDefs: Unknown tag "targetmoveerrorr" in "hyperion_karganeth_cannon"
[f=0000000] Warning: WeaponDefs: Unknown tag "soundwater" in "marauder_armmech_cannon"
[f=0000000] Warning: WeaponDefs: Unknown tag "largemeamlaser" in "nsaagriz_k666blaster"
[f=0000000] Warning: WeaponDefs: Unknown tag "canatackground" in "nsacbehe_cor_behegoli"
[f=0000000] Warning: WeaponDefs: Unknown tag "minbarrelangle" in "shocker"
[f=0000000] Warning: WeaponDefs: Unknown tag "paralyzertime" in "tllbug_tlllight_paralyzer"
[f=0000000] Warning: WeaponDefs: Unknown tag "flighttimer" in "tllfirestarter_armkbot_missile"
[f=0000000] Warning: WeaponDefs: Unknown tag "paralyzertime" in "tllgladius_tlllight_paralyzer"
[f=0000000] Warning: Could not load sound from def: null
[f=0000000] Warning: WeaponDefs: Unknown tag "bursrate" in "tlllmt1_armrl_missile"
[f=0000000] Warning: WeaponDefs: Unknown tag "flighttimer" in "tllotter_armkbot_missile"
[f=0000000] Warning: WeaponDefs: Unknown tag "paralyzertime" in "tllotter_tlllight_paralyzer"
[f=0000000] Warning: Could not load sound from def: null
[f=0000000] Warning: WeaponDefs: Unknown tag "paralyzertime" in "tllstuner_tllstuner_gun"
[f=0000000] Warning: Could not load sound from def: null

**Comment by skymyj** [comment]
OK. I can help if you want.
Is it possible to merge last commits ? 
I could cleanning after manually some units.

**Comment by nixtux** [comment]
Don't worry about thoses for now, I've pushed all the fixed needed for next engine, and set host3 up with same engine what we need now is testing

**Comment by skymyj** [comment]
If you can make the new release for tonight, it will be cool !
No more changes to do.

**Comment by nixtux** [comment]
Fixed
