### ISSUE TITLE
Tech Center Balance

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#773]
I thought about 2 things for few weeks. 
Is it possible : 
- to limit tech center to 1 => abusive use in some maps & possibility to autodestroy to counter a rush => used as nuclear mine.

OR

- Delete explosion & put same than a CRAWLER_BLAST. (except level 3 or 4, they could keep the original explosion)

Precision : I love them, but not logic than a reasearch center exploses like a nuke. No sense imho.

**Comment by nixtux** [comment]
Leave well alone, its been part of the game play from the start
