### ISSUE TITLE
Water HLT won't shoot over shark teeth

### ISSUE THREAD

**Issue by konecat** [n3wm1nd/TA#777]
Water shark teeth, obviously 

EDIT: Only tested ARM, but probably COR and TLL factions are also affected.

**Comment by playerO1** [comment]
HLT = Hight Laser Tower?
shark = submarine?
I thin it's ok - ground weapon can not effective atack underwater target. So, submarine can not attack by torpedo hower unit.

**Comment by konecat** [comment]
playerO1, https://en.wikipedia.org/wiki/Dragon%27s_teeth_%28fortification%29

Shark Teeth is the same, but on water. Yeah, we have dragon's teeth that work on water. Refrain from proposing anything on TA if you don't know units. kthx

**Comment by nixtux** [comment]
That's sounds like aim from is set wrong in unit script

**Comment by nixtux** [comment]
Cant reproduce will close (but did fix tll floating hlt)
