### ISSUE TITLE
New Idea : Advanced "Tesla/Laser/Terra"-walls

### ISSUE THREAD

**Issue by frameworld** [n3wm1nd/TA#790]
TLL-"Tewal" : This wall zaps every unit between 2 Tesla-Walls
Arm-"Suwall" : Stuns units which get pass trough, but takes energy per unit.
Core-"Lawall" This wall builds up charge for each Wall in the "network" which unloads on targets.

Why? It
* does not block own units
* has less build spots (1/15) and thus less stop+go for constructors.
* can be disabled when the gaps between are big enough after one is killed.

possibility to upgrade it with:
* LLT gun
* regenerator (auto-repairs itself)
* Stealth/Cloak
* Pop-up ability (adds armour while no enemy is near)

Upgrades could be spawned drones to allow multiple upgrades (up to 3-5 total) which spawn on a stick on top of the wall.

**Comment by skymyj** [comment]
Why not, but I think it will be a lot of work for developpers :)
& it's maybe not the priority

**Comment by frameworld** [comment]
I can understand that.
I just think it is important that defence remains defence rather than offence and this is a good (currently) unique thing that can't be used as offence (thus can be more cost-efficient and still balanced).

**Comment by nixtux** [comment]
Wont do
