### ISSUE TITLE
complaints from facebook

### ISSUE THREAD

**Issue by Bla1** [n3wm1nd/TA#792]
Some things I noticed that are now annoying, or still annoying. 
-Arm apparently don't have a Airpad anymore 
-Arm doesn't have hardened helpers anymore 
-Airports still have the annoying glitch where if you setup a patrol route and then start producing planes it'll cancel the order once the first plane is produced.

(Taken from a facebok post on our page)

**Comment by skymyj** [comment]
- AirPad for you is the "Automatically Repairs Aircraft" ? If yes, you can make this structure with Air T2 constructor. I think it's possible to add to T1
- Hardened is it the nano ?

**Comment by ruffngod** [comment]
Found both the helpers and airpad. Interesting changes.
-Still the issue with the airports.

**Comment by nixtux** [comment]
-Airports still have the annoying glitch where if you setup a patrol route and then start producing planes it'll cancel the order once the first plane is produced.  Fixed
