### ISSUE TITLE
[f=0118884] Error: CobError: Unknown get constant 0 (params = 0 0 0 0)

### ISSUE THREAD

**Issue by abma** [n3wm1nd/TA#807]
happened in late game, sorry can't provide more details

 Tech Annihilation v2.36.5

**Comment by abma** [comment]
also the game didn't end.

[f=0000000] GameID: 7f3003568fb00f216eab4300b9633735

http://www.filedropper.com/20150924014305smallsupremebattlefieldv2100

**Comment by nixtux** [comment]
Fixed script errors here https://github.com/n3wm1nd/TA/commit/f9f20f2231ec65e52e09433777a0479c87caa79f

will close
