### ISSUE TITLE
TLL - Orbital Ion Cannon

### ISSUE THREAD

**Issue by h4nn3ss** [n3wm1nd/TA#834]
Plz remove or adjust this unit. Its op . Only takes 20k E and is infinite and has wide range.

imo it should cost at least 100k e to use or smaller range

**Comment by skymyj** [comment]
Hmm. Sure we can adjust it. 
& If its cost is same than Vulcain T4 ? (with m&e ratio for tll)
With like 60KE/S (TLL produces less energy than ARM/CORE) ?

**Comment by skymyj** [comment]
An Adv Fusion gives +1000E.  (13000M)
& an Dark Matter gives +3000E. (89000M)
So if you have to make Dark Matter * 20 to use the TLLION. 

I think 25KE should be fair enough. 
Range is fair (it's an space weapon & there is no range limit)
So we can reduce the AOE. (1200 => 600)

**Comment by nixtux** [comment]
Revert OP weapon https://github.com/n3wm1nd/TA/commit/f0f2f77b22281b5bb3d8bfcfb500eea1c8986c7c

**Comment by skymyj** [comment]
You should revert Metal & Energy cost too. 
Cause it just UP unit now...

**Comment by nixtux** [comment]
I buffed weapon slight when i reverted it, cost can stay for now
