### ISSUE TITLE
T1.5 Construction Vehicule Bug

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#836]
Whebn you make a Research Center lvl1 to construct an advanced Contruction Vehicule & after you reclaim this Research Center, you can construct all T1.5 Unit. 
I think, the T1.5 builder unlock these units like Research Center. 
Is it possible to fix it ?

**Comment by nixtux** [comment]
I take it you mean fred and marv ?

**Comment by skymyj** [comment]
Yes Sir :)

**Comment by nixtux** [comment]
Bug has nothing todo with fred or marv, will push fix to tech gadget
