### ISSUE TITLE
tesla (tlltesla) to morph into charged tesla (tlltesla1)

### ISSUE THREAD

**Issue by Bla1** [n3wm1nd/TA#841]
I mean seeing how the reliser can morph into happlic, the tesla might as well morph into the charged tesla

**Comment by skymyj** [comment]
I did change for TLL morph. But Nixtux don't want any morph for TLL.
I will delete TLLHLT & TLLplasma.
For charged Tesla, I think you could make with assault commander or by combat ?

**Comment by Bla1** [comment]
Hm, TLL combat is quite weak compared to arm/core, I think it could use charged tesla. BTW, I still think we should keep TLLHLT and TLLplasma, they are fine as is

**Comment by skymyj** [comment]
Bla1, what do you think about these changes ?
