### ISSUE TITLE
armrottweiler (second weapon)

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#854]
Hey, 

What do you think about remplace EMG canon (115dmg/s) with AA Weapon system like Panther or Coyotte.

2 Goals : 
- Add autonomy vs air to this heavy & slow unit.
- Respect the graphisms unit. It's a launcher & not a plasma canon.

![rottweiler](https://cloud.githubusercontent.com/assets/2990630/10868702/c2acfc22-8096-11e5-9a37-50e44f9f6ec2.png)

**Comment by nixtux** [comment]
I dislike the idea too simular to panther weapon + AA, and it was designed with a me to combat low level t1 spam attacking it

**Comment by skymyj** [comment]
We can remplace the Minigun by a Missile (Samson or Slasher)
