### ISSUE TITLE
[BUG] T2 Arm Panthers not firing at t2 Arm Archangels (AA)

### ISSUE THREAD

**Issue by DeathStarSPRING** [n3wm1nd/TA#857]
[BUG] T2 Arm Panthers not firing at t2 Arm Archangels (AA).

Screenshot for your convenience:
http://imgur.com/o7KYomD

Please address this issue.
Thank you.  :)

**Comment by skymyj** [comment]
Sometimes, I have bug like Pewee (&flea) can't shoot a metal extractor.
I see that happen when I Select my unit & select manually the opponent target. (with attack cursor)

**Comment by skymyj** [comment]
I think, the bug is in the widget that keep in memory the target selected..

**Comment by nixtux** [comment]
Need a short demo ie under 5 mins with this problem please

**Comment by nixtux** [comment]
The issue with some unit not shooting mex's can't be fixed, ive made there hitsphere as small as possible already

**Comment by DeathStarSPRING** [comment]
Hi nixtux.  Here is a link to a video showing the bug:
http://www.veoh.com/watch/v96652545k5258zZY


P.S.  Maybe it has to do with those archangels being surrounded by metal wrecks?

**Comment by nixtux** [comment]
Thanks fixed, you will see a massive improvement with all unit firing btw
