### ISSUE TITLE
Naval Morph

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#860]
Actually, all units categories have morph option except naval (& copter..but i didn't like them :) so i will not speak about them). 

So, what do you thing about : destroyer could morph into cruiser. With 0.50 xp & 60 seconds ?

![corroy](https://cloud.githubusercontent.com/assets/2990630/10965658/eb7a7b0a-83ae-11e5-8353-c37f3c530347.png) => ![corcrus](https://cloud.githubusercontent.com/assets/2990630/10965661/eb82cd00-83ae-11e5-8b1b-47b065abd4cf.png)
![armroy](https://cloud.githubusercontent.com/assets/2990630/10965659/eb7fb30e-83ae-11e5-9731-7a5f33da708b.png) => ![armcrus](https://cloud.githubusercontent.com/assets/2990630/10965660/eb81bd7a-83ae-11e5-801e-5afc9eed4cda.png)

**Comment by nixtux** [comment]
Tll sea is already weak, if arm/core had morph the balance would be even worse

**Comment by skymyj** [comment]
Maybe Add Morph for TLL too :)

**Comment by frameworld** [comment]
I am against a T1→T2 morph.
Arm/core sea-mexes (T1 and T1.5) are imba enough :p

But I'd like hover-cruisers having more siblings (also anti-uw) and actually be immune to torpedoes (hovers are too).

**Comment by Zonkspring** [comment]
I like that idea, at times i was thinking about suggesting exactly that. 
Destroyer and Cruiser have exactly the same Job (skirmishing and anti-sub) anyways.

Perhaps also Corvette -> Anti-Hover cruiser -> Battleship (all 3 can only fight surface stuff). But should need a lot of xp, hard to say how much exactly... 0.50? 0.70?
and Scoutship -> AA-Ship (AA is the job of both)

**Comment by frameworld** [comment]
OK, scout→AA is not that op, because AA is conditional and may also be a resource-sink, so T1→T2 is ok here.
The hop over Anti-Hover-Cruiser is good for corvette too, tough land units stop at T1.5, so it should really need enough exp.
