### ISSUE TITLE
Core (?) Uppercut (t3 nuke sub) (unitname: uppercut) responds to Ctrl C

### ISSUE THREAD

**Issue by Bla1** [n3wm1nd/TA#863]
When you press control C, it will select that unit

**Comment by nixtux** [comment]
yep control+c is used to cycle through all units with canmanualfire tag set true, uppercut is one of them, and its done via engine not mod side

**Comment by Bla1** [comment]
Shouldn't we change it to normal fire like nukes and tacnukes have?

**Comment by nixtux** [comment]
NO !!!, if we did that tac nukes will auto aim at target's (for example ones inside your own base) need i say more :P

**Comment by Bla1** [comment]
well ofc make it hold fire

**Comment by Bla1** [comment]
In fact do nukes/tacnukes even have an engagement setting? They're hardcoded to hold fire right? So should uppercuts

**Comment by nixtux** [comment]
The fire states are a unitDef setting would effect both weapons so can't be used, having it command fire would work as you suggested but then when you aim  with attack etc, the other weapons the unit has will try to attack there which is unwanted also, trust me the way it is set now is the best

**Comment by skymyj** [comment]
+1 with Bla. Delete other weapons from Tac Sub & apply bla suggest.

Torpedo Weapons are good (for defense) but the strategy imho can be, escort your tac Sub. 

It will be more easy to attack target.

**Comment by nixtux** [comment]
Nope
