### ISSUE TITLE
tlldmc unlock by T3 factory & not by Star Com.

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#868]
Actually, if your commander dies, you just can't make this unit...

So, is it posible to unlock this unit.
If not, I think T3 Lab could unlock this unit. 

https://github.com/n3wm1nd/TA/wiki/tlldmc

**Comment by Zonkspring** [comment]
Would be good. Arm & Core also can make their Anti-T3 guns without Commander.
