### ISSUE TITLE
Mines Lock & Unlock

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#869]
Actually, there is a no sense for Lock/unlock strategy Mines.

Actually, it's possible to make Nuke Mines & not make heavy Mines.. 
Cause => Heavy & EMP mines are locked by T1 research Center & Nuke Mines by T2 Lab.

We have to have : 
Heavy & EMP => unlock by T1 Research Center (actually it's fine)
Nukes Mines => unlock by T2 Research Center (So, if T2, you can make all mines).

For TLL, it's fine. T2 Lab unlock them.

Thanks.

**Comment by nixtux** [comment]
Yep total fine change
