### ISSUE TITLE
[BUG] Sync errors

### ISSUE THREAD

**Issue by DeathStarSPRING** [n3wm1nd/TA#872]
Many new players, when joining TA, have sync errors in-game (like Ashavir).  I had a sync error in-game as soon as the game started on blue fields (I never encountered a sync error on blue fields before) earlier today and only fixed it by re-downloading a portable version of spring 100 and re-downloading most everything else (the only things i saved from the old portable version includes widgets, maps, uikeys.txt and springsettings.cfg).  Maybe it has something to do with the latest TA version or how it updates/updated?  
Please address this issue.
If you need further information, please ask.
Thank you Nixtux and devs.

**Comment by nixtux** [comment]
Fixed
