### ISSUE TITLE
Commando  Strategy

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#877]
Actually, only Owl uses this unit... 
![commando](https://cloud.githubusercontent.com/assets/2990630/11557828/3da12210-99af-11e5-8f29-fe92c474ee9d.png)

Is it possible to add a new use for this unit.
Goal is to add in Assault Com Panel. (So delete from Helper). 
Add Jump feature to follow & support assault commander. 
Cost should be increase (like 3~5 K Metal), cause he could makes structures &/or units.
I think about pop-up & morphing T2 units like Goliath Sumo...

\\\\\\\\\\\\\///////////////////////...Before.../////////\\\\\\\\\\\///////////////////////\\\\\\\\\\\\\///////...After...
![capture](https://cloud.githubusercontent.com/assets/2990630/11558250/daca8322-99b1-11e5-82ca-8745b20be335.JPG)

Finally, goal is to let more the choice between 'commander' or 'Research Center/Lab'  branch

What do you think ?

**Comment by frameworld** [comment]
I often use Commandos when I can access T1.5 eco with a shared T1.5 flying con.

But eco com and unit spam is easier on greenfields.

I think T1.5 lives too shortly. I prefer more micro-managing of morphed stumpies, etc. Then it would make sense to build Commando more often.

In the crowded 10+ peoples hosts, building T1.5 combat with more than 1/5 of your team is wasting time before T2 eco.
