### ISSUE TITLE
Commander too easy to emp with CORE T1 Air Bladewings?

### ISSUE THREAD

**Issue by DeathStarSPRING** [n3wm1nd/TA#888]
Commander too easy to emp with CORE T1 Air Bladewings?
Is this intentional or should the commander requires more paralyzers?
Attached is a screenshot for your convenience:
http://imgur.com/llc3Sx0

Please address this issue.
Thank you Nixtux and Devs.  :)

**Comment by skymyj** [comment]
+1 with deathstar. Divide by 2 emp damage for commander pls

**Comment by nixtux** [comment]
Fixed With https://github.com/n3wm1nd/TA/commit/14d1e275a56941a03b157559d5aae5c979e91904
