### ISSUE TITLE
Wrathful Zeus might need slight boost (armzeus1)

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#899]
Upgraded Zeus compared to Can:
758 vs 705 Cost
52 vs 40 Move
300 vs 275 Range
200 vs 343 Dps - Yes, im aware LightningCannon has less damage dropoff at range, but they are Assaults, so hey. They're meant to be rammed into the enemy (unless ur using Zeus and fighting vs Cans, I suppose).
Drawback of LightingCannon is that Zeus has a much harder time hitting scoutspam, missing often. Can are a lot better at that due to having double the ROF and higher accuracy.

Very similar, all of those stats - no?

However - Last but not least, heres the biggest difference:

Cans can be made from factory, hell, they can even be made by Freakers.
Wrathful Zeus - u need to build a Zeus (only from T2 Factory), let it get experience, and THEN, FINALLY, Morph it - after it most likely already took damage - in the middle of the field. 
For 30 seconds, during which it is not just completely useless, but also very vulnerable.

I think we all agree that morphs should be "worth it" and that morphed units should be noticeably better than their unmorphed counterparts.

Suggestion: BUFF Wrathful Zeus. Or make the cheaper but I think a buff is the better solution.
Suggested buff would be:

- Increasing DPS from 300 dmg / 1.5 sec (200 DPS) to 300 dmg / 1.2 sec (250 DPS)
- Increasing HP from 5000 to 5300
- Increasing Range from 300 to 330, probably won't be noticed very much, but at least this means a 50 range increase after the morph instead of just 20. And now they can skirm Coms... and Cans.
- Decrease morph time from 30sec to 20sec. 
It ain't no Golli or Sumo, its a mass unit, like Hammers or Rockos - such Units need low morph times or after morph they'll just stand on the edges of the battlefield, forgotten and deserted while their owner fights with on his remaining (unmorphed) army.

Personally I think all of those are relatively moderate Buffs... but imo its better to buff moderately than to end up with OP units and everyone screaming nerf.

**Comment by skymyj** [comment]
Ok done. (I just limited damage fixed to 250)
Nixtux takes the final decision.

**Comment by Zonkspring** [comment]
Thanks, sounds good. :)

**Comment by nixtux** [comment]
@zonkspring "im aware LightningCannon has less damage dropoff at range"  not less it's none, they deal full damage at any range

**Comment by nixtux** [comment]
Merged
