### ISSUE TITLE
Very Heavy Anti Air Flak Guns (armhys / corpre) are strange.

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#900]
Everything about them is same or so similar that it makes no difference, except for:
armhys 6500 HP, 1200 range, 20 fake-dps, 128 aoe, 75% edge
corpre 8500 HP, 1050 range, 25 fake-dps, 128 aoe, 50% edge
That intended or...?
Imo having 150 more range is more useful than having 20% more dps.
Especially when armhys has 25% more edge damage.
HP differences... seem pretty irrelevant. If T3 and even more so T4 fires at either one, they will melt like Ice in the Sun.

However, another thing - and heres where it gets really funky:
Both cost 15,5k.
For that cost I can build 9 regular Flaks.
Each one has:
975 Range, 96 aoe, 85% edge.. and 16.67 fake-dps (total: 150 fake-dps)
Also, I can spread those out... and they got about 18-20k more HP than Very Heavy Flaks.

Now I don't know the real DPS of those flaks, but if the VH-Flaks use the same damage multipliers as regular Flaks... then the VH Flaks might really need a Buff.

**Comment by skymyj** [comment]
Few month ago, they cost like 20K metal... 
I decreased metal cost & increase damage.

For damage : 8000 dmg/s (corpre) vs 2000 for classic. (&6400 for armhys)
I propose special damage versus bombers. Like 14k dmg/s & increase range for both (+150).

What do you think ?

**Comment by Zonkspring** [comment]
Ah, nice to know real damage values. Special damage vs bombers increase sounds good.
At first look 14k dmg/s seemed very high, but considering that Cyclone has 12k and Eclipse 22k hp (and costs half of T3 flaks) something like 12-14k dps vs bombers might be a good idea. 

Range increase - absolutely agree.

**Comment by skymyj** [comment]
To see all values, go to the wiki. 
https://github.com/n3wm1nd/TA/wiki/Units
And type name of the searched unit : https://github.com/n3wm1nd/TA/wiki/armhys

**Comment by Zonkspring** [comment]
Aah, thats how that Wiki works, thanks!
I tried to click on the pictures - no link. "Aha, wiki not finished" I thought =)

**Comment by SoulRaiZor** [comment]
Or better u go direct in the .lua file.
https://github.com/n3wm1nd/TA/blob/master/units/armhys.lua
for example - there u have all info about a unit

**Comment by nixtux** [comment]
The only click able pic on wiki start page are commanders, I did try more but github grinds to a halt

**Comment by nixtux** [comment]
Merged skymyj buff

**Comment by skymyj** [comment]
Forget to increase range & dmg for tll t3 flak.
If you can do it. Thanks

**Comment by skymyj** [comment]
Is it possible nix tio reopen it.
Now TLL Flak have 4800 dmg / s at 1150 range & 1500 at 1700 range. 
I balanced with ratio metal & energy cost for TLL
