### ISSUE TITLE
Morped Sumo Morphed Golli (Corsumo1 / Corgol1) armorclass

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#901]
Armorclass of both before morph: raider_resistant
Armorclass of both after morph: default
Probably not intended, since other units also keep their armorclasses after morph.
Not that I think either one really needs raider resistance, as they tend to tear thru those anyways, but...

**Comment by nixtux** [comment]
fixed with https://github.com/n3wm1nd/TA/commit/cb62377b588666a079ca2f4965d69370d0cdf3b3
