### ISSUE TITLE
My homeboys Marvin and Fred (armmarv, corfred) and the story of the amphibious mexes

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#902]
Both of those can not just build T1.5 mex (Overcharged Metal Extractor, Amphibious) but also regular Underwater Mex. However, strangely they can not build regular T1.0 Land mex.
But why bother with either kind of T1.0 mex anyways when u can build T1.5 Mex?
Those guys don't have any of a more reason for building a T1.0 mex than a T2 cons has.

Suggestion: 
Remove 1.0 Underwater mex from T1.5 Amphibcons. No real reason for them to be there.

Also one fix is needed:
Upgmex command for Marv and Freddy does not recognize Underwater T1.0 Mexes as "Mexes to upgrade" - so when you are a sea player and have only UW T1.0 Mex and set ur Marvfred to "UpgMex On" it will tell you "No mexes to upgrade".

And then you hit "Z" to upgrade your mexes - intending to place the T1.5 mexes next to ur 1.0 mexes... and select UW mex instead, cuz those are also in the buildmenu, for no real reason. 
Now you "doublecap" ur mexspots with another UW 1.0 mex. Trolololo!
Pleze fix this mess. :dancers:

**Comment by nixtux** [comment]
Part fix https://github.com/n3wm1nd/TA/commit/c949ae0168acfcc5a128cdf306649e22e4fe6360
