### ISSUE TITLE
Tech Annihilation, BA and how I learned to love the (Com-)bomb

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#905]
As some may know, I've used to play a lot of BA.
After a long, long time with regular Combomb (and massive complaints, along with the usual - "just make AA" counterargument) there, BA devs decided to nerf it by reducing the airblast-damage.

So now in BA you can only Combomb by either walking or actually airdropping your Commander next to the enemy Commander - and then starting selfd or getting killed by units/porc.
(You can start selfd before picking ur com up, but it will be cancelled the moment u airlift him. 
You can not dgun the enemy Commander, because after a drop your Dgun has to "recharge".)

Imo - when you manage actually drop your com next to the enemy com, you deserve to Combomb successfully. Dgun shouldn't have to recharge.

But after you've played for a while with reduced Combomb airblast damage - you really start to notice how brutally OP regular unnerfed combomb is. 

Airblasting enemy com is just a bit too easy. Even when your com is trailing a handful of crashers behind him, they might be blocked - or shoot so late that your com will be caught by the airblast anyways.

Suggestion: Reduce airblast damage, like it was done in BA. 
Just don't also copy that D-gun recharge nonsense, having to actually drop the com for combomb is hard enough by itself.

Talked with Solve about this btw and we came to the same conclusion.

**Comment by SoulRaiZor** [comment]
We dont have the problem of many combombs here.
I think its because com is much more useful in TA than in BA.
We can talk about it later again :D

**Comment by Zonkspring** [comment]
Yeah, TA coms are more useful than in BA so people don't want to lose them. 
But 4k Metal are very useful too and enemy also loses his com... or get 2k metal and rez ur own com. xD

**Comment by nixtux** [comment]
We do use a custom gadget to reduce combomb damage (damage is reduce to the commander with the greatest hp)

**Comment by nixtux** [comment]
https://github.com/n3wm1nd/TA/commit/21c19dab5eb1bdbc0a112008b3331424cddda3b4
