### ISSUE TITLE
Mole - Core Vehicle Combat Engineer Buildrange (corassis)

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#910]
Core and Arm Vehicle Combat Engineer (Consul) are 99% the same, except for 1 critical difference:
Consul has 136 Build radius, Mole just 92.
This often means Mole have massive problems trying to start buildings. 
Especially when working in groups, the Moles in the rear push the front Moles forward - into the building zone, before it is started - blocking the building. Moles drive back, Moles drive forward, building still isn't started (/RAGE, "Mole stop acting like ***hole!" :D ).
Start a DD with 10 Moles - almost impossible. Sometimes it works on 2nd try, sometimes on 10th, sometimes never. Need to start building with one, others on guard. Much extra micro, with 10 Consul its no problem to start Annihilator on the first try.

Sometimes even a single Mole will have problems starting a Viper on the first try if it drives a little bit too far.

Please give Moles same range as Consul (136), thanks! :)

**Comment by skymyj** [comment]
Done. Just wait nixtux Merge

**Comment by nixtux** [comment]
Merged
