### ISSUE TITLE
Defiler : Balance AA Weapon 

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#921]
Actually, his weapon is very powerfull. (best AA for mobile unit (except flak))
range = 800
burst = 2 
reload = 2
dmg {
bombers = 250,
default = 5,
fighters = 250,
flak_resistant = 250,
unclassed_air = 250,
}

= 250 dmg / S at range 800 :x: I propose to decrease to 200 dmg/s & range at 600.

**Comment by skymyj** [comment]
Maybe just fix range to 650

**Comment by Zonkspring** [comment]
Its AA seems pretty crazy. I agree a small nerf might be needed, 200 / 600 sounds ok.
