### ISSUE TITLE
Termite weapon

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#923]
hey, 

Is it possible to change visual effect for his main weapon. 
Gold beam is for T4 Krogoth (& if possible for T4 Corgala).

I'm for the same green beam than corcan.

**Comment by Zonkspring** [comment]
But T4 Krog has Blue Laser? Like T3 Krogoth and Annihilator.
Also, Termite has this Heat Laser since ages, many got used to it, I like it - its unique.

**Comment by frameworld** [comment]
I agree with Zonk, except you want one colour per tech level (red,green,blue,gold).

But I like colours to indicate factions too. Supreme commander - forget alliance had nice faction colouring with these 4 colours.

**Comment by skymyj** [comment]
Turtoise remplace it.
