### ISSUE TITLE
Butcher & Arm Anti T3/T4

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#928]
What do you think about deleted these weapon from T2 Cons ? 
Add for T3 Cons.

**Comment by SoulRaiZor** [comment]
why?

**Comment by skymyj** [comment]
Cause, they are too powerfull versus T3/T3.5.
& Cause, they are better than Adv Tachion or Adv Doomsday. (damage & range for core).
I think, it's logic than the best defense have to be construct by T3 cons.

**Comment by SoulRaiZor** [comment]
But Fury and such can be built with lab from T2 con.
Only Chance to def them is dgun then?

**Comment by skymyj** [comment]
T3 air gunship do the job. Champion and antarion too.

**Comment by nixtux** [comment]
Imo they are needed you need a way early on in the game to counter such units, I won't be deleting these from t2 con build menu
