### ISSUE TITLE
Balance TLL Side, Battle commander should be able to build flametower

### ISSUE THREAD

**Issue by Senna** [n3wm1nd/TA#930]
TLL side is very underpowered, right now battlecommander needs an buff, and also be able to build the flametower

**Comment by SoulRaiZor** [comment]
Ya TLL sucks atm - almost no one is using it.
Battle com has no special unit, so not needed to update

**Comment by skymyj** [comment]
Could be good to add a special unit like helepolis. (Decrese stats and cost)

**Comment by Gambit99** [comment]
I am looking at individual tll t1 units, considering dps * maxdamage / metalcost. I then look at other factors like range and movement more judgmentally. I think that a few units (riot tanks, for example) could use a small buff.

**Comment by Gambit99** [comment]
Currently the flamethrower is more like a t1.5 turret, but you need an assault commander to build it. The assault commander morph has costs similar to T2.5 tech, so it would make sense that this turret should come earlier on the battle commander.

**Comment by skymyj** [comment]
+1 with Gambit. 
I even say, we should delete this unit. What job for this tower ?

Goal actually, is to delete useless units to have a better balance & gameplay.
