### ISSUE TITLE
More TLL side issues, t2 burner, they are very slower and mutch worse than pyros

### ISSUE THREAD

**Issue by Senna** [n3wm1nd/TA#931]

**Comment by skymyj** [comment]
Have you seen how they walk? 
Just illlogic to fix zame spedd than pyro. 
They have better stats except speed.

**Comment by skymyj** [comment]
Damage * 2, better Range. 
Speed 2.0 vs 2.7
Cost * 2. 

It's just maybe Pyro cost is cheaper. Corst E is only 2K. Maybe increase to 3KE.
