### ISSUE TITLE
NoSelfDamage for TLL Riot (Pacifier)

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#959]
To balance with Riot Tanl Leveler. 
Actually, they are too weak. Cause they kill themself.

**Comment by Gambit99** [comment]
I like this too. This is like a bug fix since they should not be hurting themselves. In a large clash they do kill everything including themselves.

**Comment by nixtux** [comment]
Adding nonselfdamage will not fully limit damage, only damage dealt by unit, it will still be effected by the extra that the area damage gadget produces

**Comment by Gambit99** [comment]
I have extended the gadget to make use of an `allyScale` and `teamScale` attribute in the `area_damage_defs.lua` file. See PR #964
