### ISSUE TITLE
Floating UW Afus (crnns, armuwfus1) 

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#966]
Arm and Core UW Afus are floating - Core can be closed, Arm can't. 
Perhaps Arm UW Afus were meant to be underwater instead of floating?
The other thing thats making me think this is that they look exactly like regular Arm UW Fus - unlike the Core UW Afus, which look very different from normal Core UW Fus.

**Comment by nixtux** [comment]
@Zonkspring zonk you on about the Arm's Advanced Antimater Fusion ?

**Comment by Zonkspring** [comment]
Yeah, its the one thats built by t2 seacon.

**Comment by skymyj** [comment]
Why not :)

**Comment by nixtux** [comment]
I don't see a problem with this infact it make sense as crnns is armored, this unit is at a disadvantage compaired to it counterpart
