### ISSUE TITLE
TLLRID

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#974]
Balance Timebuild. 
9000 => 49000 (same than ground laser tachion)

**Comment by nixtux** [comment]
IMO tll sea is weak tlltrid should be cheaper than land version on the same cost!!!!!!!

**Comment by nixtux** [comment]
ie https://github.com/n3wm1nd/TA/commit/d0ee7e7a40e5b9f91f511089e64c95872ecb9ddd

**Comment by skymyj** [comment]
Fine for me. Thx
