### ISSUE TITLE
Happlic High Trajectory

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#982]
Guardian has High Trajectory, T2 version is Ambusher and also has High Trajectory.
Punisher has High Trajectory, T2 version is Toaster and also has High Trajectory.

Reliser has High Trajectory,  T2 version is Happlic (tllplasma) - no High Trajectory.
Perhaps a High-Trajectory mode could be added? Would be cool. Or is that hard to do because of Happlic's model?

**Comment by frameworld** [comment]
Hard to do is not a reason (see "Exception").
Normal: 0…45° --with 45° firing the furthest and 0° straight forward
High-Traj: 90…45° --with 45° firing the furthest and 90° to target nearby
Exception: if( High-Trajectory AND angle > supported ) then (fallback to 0…45° calculation)

I'd like an auto-mode too. Use high-trajectory if low-trajectory (isn't feasible on any target) or (targeting a static).

**Comment by nixtux** [comment]
The latter, hard todo due to model
