### ISSUE TITLE
Amphib complex explode while being built

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#983]
Same for both Arm (asubpen) and Core (csubpen), can't build them - they explode before being finished.
= no Amphibs, no Marvin/Fred D:

Thx for Marvin/Fred fix btw (and all the other stuff ^^)

**Comment by nixtux** [comment]
Ah is because there factorys (have canmove set true) there getting miss identiyed as ships in the gadget which control explosion
