### ISSUE TITLE
TLL Built-in MM keep converting even when stalling

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#984]
The Metalmakers that come included with TLL Geos and Fusions will continue converting even if their owner is stalling E for quite some time, feels like it takes forever for them to stop converting despite E-Stall.

Maybe they could be set up to stop converting a lot earlier?

**Comment by nixtux** [comment]
There not controlled by the same gadget that arm/core MM, so they don't turn off unless you turn the whole unit off

**Comment by Zonkspring** [comment]
Hmm, can't even do that (turn them off) :/
Would it be possible to setup the widget controlling tll geos & fuses in the same way as the normal mm widget?

**Comment by nixtux** [comment]
No!!, 2 reasons first you would turn any energy output off, 2 the reason MM use a gadget now to control them is to reduce the amount of command spam that was sent to turn them on and off

**Comment by nixtux** [comment]
Closing
