### ISSUE TITLE
Github - sorted by newest

### ISSUE THREAD

**Issue by Zonkspring** [n3wm1nd/TA#985]
Current setting is: Sort By Newest (Issue/Pull request)
Maybe it would make sense to change it to: Sort By Recently Updated?
Makes comments in old Issues easier to see, its the same setting as used by most Forums.

Also, I just noticed we have a Tech Annihilation Subforum at the springrts forum now, nice. ^^
https://springrts.com/phpbb/viewforum.php?f=91

**Comment by skymyj** [comment]
it's time for the TA baby to take off

**Comment by SoulRaiZor** [comment]
yeah nice 
+1 zonk

TA is morphing to the biggest spring mod ! :dancers:

**Comment by frameworld** [comment]
+1
But I also like to have a list of newest topics which I didn't have looked into jet.

Is it possible to have that side-by-side or 2 sections above/below each other?

**Comment by nixtux** [comment]
N/A
