### ISSUE TITLE
Nerf Nsacskv

### ISSUE THREAD

**Issue by skymyj** [n3wm1nd/TA#988]
If you compare with correap (reaper) :
Metal cost - 635
Energy - 12000
Damage/s - 137.5
Range - 410
Speed - 2.3
MaxDamage 5750

nsacskv :
![nsacskv](https://cloud.githubusercontent.com/assets/2990630/12875106/2a0b5af0-cde3-11e5-98a2-1e97d3b345d7.png)
Metal cost - 500
Energy - 10000
Damage/s - 320
Range - 700
Speed - 2.75
MaxDamage - 2850

For good balance, please, just decrease MaxDamage to 2000

**Comment by SoulRaiZor** [comment]
TLL needs push, not nerv.
Just play it if u think it is so op.

**Comment by skymyj** [comment]
Don't understand.
It's a core unit.

**Comment by SoulRaiZor** [comment]
ah looks like TLL to me :D
