### ISSUE TITLE
(v2.38.19) debug message spam or something Value 1: 9, 2 ...

### ISSUE THREAD

**Issue by knorker** [n3wm1nd/TA#998]
I joined a match as spectator and after a while these messages spammed the chat:

> [f=0107470] Value 1: 9, 2: 0, 3: 0, 4: 0
> [f=0107474] Value 1: 9, 2: 0, 3: 0, 4: 0
> [f=0107478] Value 1: 9, 2: 0, 3: 0, 4: 0
> ...

It continued to spam after /luaui disable

[infolog.txt](https://github.com/n3wm1nd/TA/files/168116/infolog.txt)

[20160310_222700_GeoGreenField_fix_v6K_101.zip](https://github.com/n3wm1nd/TA/files/168117/20160310_222700_GeoGreenField_fix_v6K_101.zip)

Spring 101.0
using map: GeoGreenField_fix_v6K
using game: Tech Annihilation v2.38.19

**Comment by nixtux** [comment]
already fixed with https://github.com/n3wm1nd/TA/commit/d0f786ddbc857715c976e475db965df64a3b0e45
